### ISSUE TITLE
Add ability to edit file/headers

### ISSUE THREAD

**Issue by ikkisoft** [electron/fiddle#100]
It would be cool to be able to the edit the filename (and consequently the window title) for the three windows view. 

![screen shot 2018-09-26 at 10 22 25](https://user-images.githubusercontent.com/6027823/46067014-16587e00-c176-11e8-88cf-e728fbfc0647.png)

For example, if you want to experiment with preload files - it would be nice to rename renderer.js into preload.js and adjust the window title bar too. This will also give more flexibility to the tool.

It would be even better to be able to remove windows and add new windows (with custom filename/title).

**Comment by erickzhao** [comment]
Although this issue isn't currently being worked on, PR #254 is proposing to add a `preload.js` as an optional Editor window!

**Comment by codebytere** [comment]
@ikkisoft i think this is functionally addressed by https://github.com/electron/fiddle/pull/636 - are you ok with my closing this out?

**Comment by ikkisoft** [comment]
Yes, absolutely! thanks for the follow-up
