### ISSUE TITLE
Coverage Decrease Threshold for failure

### ISSUE THREAD

**Issue by BlackHole1** [electron/fiddle#1002]
Errors will be reported even if the coverage is reduced by `0.01%`

This is too strict. Perhaps it would be better to adjust the threshold to `0.1%` or `0.05%`

Ses: 
* https://github.com/electron/fiddle/pull/994
* https://github.com/electron/fiddle/pull/992

cc: @erickzhao

**Comment by erickzhao** [comment]
I believe only repo admins have access to the Coveralls settings. Can't access the Fiddle settings from my UI (@ckerr @codebytere or @felixrieseberg might have more luck).

**Comment by BlackHole1** [comment]
https://github.com/electron/fiddle/pull/1039#issuecomment-1098645773
