### ISSUE TITLE
Fiddle Doesn't Come to Foreground When Loading Fiddle From Browser

### ISSUE THREAD

**Issue by dsanders11** [electron/fiddle#1007]
Currently when opening a fiddle from the web browser, if Fiddle is already open, it will show you the "Are You Sure?" dialog, but it won't bring Fiddle to the foreground, so you wouldn't know it's doing so. On macOS it correctly comes to the foreground.

**Comment by akgupta0777** [comment]
I have a question how the fiddle load the code from remote.
I mean [](https://fiddle.electronjs.org/launch?target=electron/v17.1.2/docs/fiddles/ipc/pattern-2) by opening this link in the browser `electron-fiddle://electron/v17.1.2/docs/fiddles/ipc/pattern-2 `the app is launched but how it loads the code ?

I checked the `remote loader` and it can load from gist but the above URL is not a gist its a simple URL from Docs.

**Comment by dsanders11** [comment]
Hi @akgupta0777. The code for loading from the docs is [here](https://github.com/electron/fiddle/blob/main/src/renderer/remote-loader.ts#L57-L106) in `fetchExampleAndLoad`.

For this issue, however, the problem likely lies in the window management code and giving the window focus when the dialog is put up asking for confirmation, rather than the code for loading from the docs.

**Comment by dsanders11** [comment]
Yes, a fix will likely involve the `BrowserWindow` API.
