### ISSUE TITLE
NodeJS module.parent is deprecated.

### ISSUE THREAD

**Issue by akgupta0777** [electron/fiddle#1023]
https://github.com/electron/fiddle/blob/50b6656690801882a9fc907669de3002199e4d9b/src/main/main.ts#L152

In the above line `module.parent` is deprecated. I read the node Docs and they have suggested this 

![image](https://user-images.githubusercontent.com/51379307/160224841-14836806-6835-4ed6-ac4c-34d828a77fbe.png)

Should we refactor the code or keep it this way? Does using the deprecated one have any disadvantages ?

**Comment by erickzhao** [comment]
We can change it. :)
