### ISSUE TITLE
[BUG]: `Preference` Page style is incorrect on macOS

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1024]
Noticed this issue today of application header being still visible when the user opens `Preference` page :

<img width="805" alt="Screenshot 2022-03-28 at 6 48 20 PM" src="https://user-images.githubusercontent.com/53977614/160406339-c2e2b24f-3591-4b85-8421-79ba4f374955.png">

<strong>Platform</strong>: Mac OS
<strong>Platform Version</strong>: Monterey v12.1
<strong>Fiddle Version</strong>: v0.27.3 development git

**Comment by aryanshridhar** [comment]
This can be fixed by removing these CSS lines - 

https://github.com/electron/fiddle/blob/50b6656690801882a9fc907669de3002199e4d9b/src/less/components/dialogs.less#L15-L19

Maybe they weren't removed after the new UI patch?

**Comment by erickzhao** [comment]
Yeah, I think this was a regression from a recent PR.

**Comment by aryanshridhar** [comment]
Cool, I will leave this open for any new comer to come and pick this small issue :)

**Comment by aryanshridhar** [comment]
Closing this with ref to #1028.
