### ISSUE TITLE
[BUG]: version filter stays visible when entering preferences screen

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#1031]
minor bug, but if you click the version selector and then press the keyboard shortcut to enter the preferences screen, the version filter remains visible:

![image](https://user-images.githubusercontent.com/172800/162283543-b840926a-b03d-4d6c-9a5d-02585019557f.png)

**Comment by rahoolonly** [comment]
Hey. Can anyone help me. I m a beginner and I want to contribute. How can I start?

**Comment by rahoolonly** [comment]
Hey. I am a beginner and I want to contribute. I know html, CSS, JavaScript and react also. Can anyone tell me how can I contribute?

**Comment by BlackHole1** [comment]
Local launch:

```shell
git clone git@github.com:electron/fiddle.git
cd fiddle
yarn install
yarn run start
```

Files related to this issue:
* https://github.com/electron/fiddle/blob/main/src/renderer/components/commands-version-chooser.tsx
* https://github.com/electron/fiddle/blob/main/src/renderer/components/version-select.tsx#L179-L218
* https://github.com/electron/fiddle/blob/main/src/renderer/components/settings.tsx
