### ISSUE TITLE
Quitting Unsaved Fiddle Should Focus Window

### ISSUE THREAD

**Issue by dsanders11** [electron/fiddle#1036]
Same kind of issue as #1007, it's showing a "Are you sure?" modal but the window isn't focused so the behavior on macOS is trying to quit from the dock seems to have no effect since it's waiting for user input but the user can't see.

Fix should be simple, see #1018 for how #1007 was fixed.

**Comment by dsanders11** [comment]
Same issue on Linux.

**Comment by Hanaffi** [comment]
@dsanders11 @codebytere Please assign this to me too

**Comment by VerteDinde** [comment]
@Hanaffi Please just pick one issue to work on and submit a PR for that issue - particularly for issues labeled “Good First Issue”, we want to give others a chance to work on them 🙂 Once you’ve submitted/merged a PR for one issue, you’re welcome to take on another one!

**Comment by ryan-halbrook** [comment]
@dsanders11 Please assign this to me.

**Comment by dsanders11** [comment]
@ryan-halbrook, we don't assign issues to external contributors. If you'd like to work on this issue, please open a PR and we will review it. 🙂
