### ISSUE TITLE
Loading fiddle cuts off the right action buttons

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1065]
When a fiddle is loaded using the `Load fiddle` button, the right actions button gets cut off the screen. I was left wondering for a minute that were did the popover button go!

<strong>Before:</strong>

<img width="1440" alt="Screenshot 2022-05-05 at 6 46 26 PM" src="https://user-images.githubusercontent.com/53977614/166937067-7e63d3f1-6628-4b68-a49d-345a278fb6bb.png">

<strong>After loading fiddle:</strong>

<img width="1440" alt="Screenshot 2022-05-05 at 6 46 37 PM" src="https://user-images.githubusercontent.com/53977614/166937206-c673dc3c-9e4e-4629-b44d-e2bfa6bd2fde.png">

This is so because the header updates itself to add the link of the gist which takes up the major space.

<strong>Platform</strong>: Mac OS
<strong>Platform Version</strong>: Monterey v12.1
<strong>Fiddle Version</strong>: v0.27.3 development git

**Comment by erickzhao** [comment]
Yep, we should probably make this more responsive.

**Comment by BlackHole1** [comment]
Maybe we can change it to an A tag? e.g.

[gist#git short hash]() -> [gist#abcd1234]()

**Comment by aryanshridhar** [comment]
> Maybe we can change it to an A tag? e.g.
> 
> gist#git short hash -> gist#abcd1234

This will look something like - 
<img width="1358" alt="Screenshot 2022-05-05 at 11 49 17 PM" src="https://user-images.githubusercontent.com/53977614/166987901-ab8784f3-7072-469e-b2a0-d3b26a4998b5.png">

It works fine, but the user should have an atleast window width of ~1340 px. (If the user uses it in window size < 1340 px, the buttons will get cut again!)

**Comment by BlackHole1** [comment]
> > Maybe we can change it to an A tag? e.g.
> > gist#git short hash -> gist#abcd1234
> 
> This will look something like - <img alt="Screenshot 2022-05-05 at 11 49 17 PM" width="1358" src="https://user-images.githubusercontent.com/53977614/166987901-ab8784f3-7072-469e-b2a0-d3b26a4998b5.png">
> 
> It works fine, but the user should have an atleast window width of ~1340 px. (If the user uses it in window size < 1340 px, the buttons will get cut again!)

Oh. I mean is `short hash`. e.g: `gist#94d865a4`, not long hash. 😄

**Comment by aryanshridhar** [comment]
> Oh. I mean is `short hash`. e.g: `gist#94d865a4`, not long hash. 😄

Oh My bad! Was a long day!

**Comment by codebytere** [comment]
How necessary do we feel it is to have the full link there in the header at all? It can't be copied and i don't personally see much need for it given that i'm much more bothered by the buttons being cutoff 🤔

**Comment by BlackHole1** [comment]
> How necessary do we feel it is to have the full link there in the header at all? It can't be copied and i don't personally see much need for it given that i'm much more bothered by the buttons being cutoff 🤔

I basically agree with you. However, sometimes I use this as a basis to determine if it is currently a gist project or not. Otherwise, I agree to remove it.
