### ISSUE TITLE
`ContextMenu` should be disabled in Settings page

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1070]
Noticed a minor issue of the Right click `ContextMenu` which is can be seen in `Preference`/`Settings` page as well.

<img width="1185" alt="Screenshot 2022-05-10 at 10 04 39 PM" src="https://user-images.githubusercontent.com/53977614/167679743-8b23f856-4082-441b-afbe-f49b4b897750.png">

**Comment by codebytere** [comment]
@aryanshridhar would you be interested in opening a PR?

**Comment by aryanshridhar** [comment]
Cool! Opening up a pr for it!

**Comment by luciferXarya** [comment]
@aryanshridhar  may I work on this issue?

**Comment by erickzhao** [comment]
It's already assigned to @aryanshridhar so I'd leave it to him.

**Comment by aryanshridhar** [comment]
@arya-vats Sure go ahead!
I have already pushed the fix in my local branch earlier (https://github.com/aryanshridhar/fiddle/tree/Disable-ContextMenu)
Use it as an reference if you need it :)

**Comment by vikeshk1234** [comment]
i am also work this issue

**Comment by vikeshk1234** [comment]
contexMenu page #1115
