### ISSUE TITLE
"Machine Type Mismatch" after installing update

### ISSUE THREAD

**Issue by jonasmusall** [electron/fiddle#1072]
I was using Fiddle and it received an automatic update to 0.28.1 (probably from 0.27.3 since that is the only other version I found to be installed on my machine). Now, I am not able to launch the application because I get the following message instead:

![Screenshot of error window](https://user-images.githubusercontent.com/69427105/168330992-0138c62c-94de-44cf-863f-fb0de3841866.png)

There seems to be little information on that message on Google besides a few forum posts of people in similar situations, only [this page](https://errorcode.pro/STATUS_IMAGE_MACHINE_TYPE_MISMATCH/1073741838/ddk-win-nt-4.0) which contains the english version of the error: `{Machine Type Mismatch}
The image file %s is valid, but is for a machine type other than the current machine. Select OK to continue, or CANCEL to fail the DLL load.` while the last portion does not exactly match the one I got.

I could work around the issue by deleting the `app-0.28.1` directory. Interestingly, I did not do anything to `electron-fiddle.exe` — the file the error window was complaining about 🤨

### OS info
```
64-bit
Windows 11 Education
Version 22H2
Build 22616.1
```

**Comment by codebytere** [comment]
Closed by https://github.com/electron/fiddle/pull/1071
