### ISSUE TITLE
Hover labels on file tree show up when settings are open

### ISSUE THREAD

**Issue by carolstran** [electron/fiddle#1083]
👋🏼  I noticed when tabbing to your General Settings page that you can't navigate to the actual settings form. Instead, you end up tabbing through the elements on the main editor page. So then if you stop... you sometimes end up with funny floating labels like this:

![Settings page with a floating Toggle Visibility hover label in the middle.](https://user-images.githubusercontent.com/26869552/170574315-161f4ded-9785-469a-821d-612c29a4bbc8.png)

I'm guessing it's an issue with the HTML, i.e. the main editor content should be hidden semantically while the settings are open or the settings should be injected at the top of the HTML file, etc.

**Comment by carolstran** [comment]
Same thing happens for the modules search input: 

![Floating module search input on the settings page.](https://user-images.githubusercontent.com/26869552/170575568-018f3cf9-0ba0-4e87-ac16-78a07290a77c.png)

**Comment by dsanders11** [comment]
I believe this was fixed in #1181, doesn't repro for me any longer.
