### ISSUE TITLE
Heading levels should only increase by one

### ISSUE THREAD

**Issue by carolstran** [electron/fiddle#1087]
There are a few places where the HTML of the headings doesn't follow logical order. This is an accessibility issue because it makes navigating more confusing for users of assistive technology ([see this deque article for more details](https://dequeuniversity.com/rules/axe/4.0/heading-order)).

Here's an example from the Settings page, where the main header is an `h2` element then the next header is `h4`:
![](https://user-images.githubusercontent.com/26869552/170580662-98edc7a7-1808-4cfe-9f89-87806b4d05a6.png)

And another example from the Credits page, where the main header is an `h2` element then the next header is `h5`:
![](https://user-images.githubusercontent.com/26869552/170584492-6cc904d6-1d9a-41fd-b29a-154c8b5cfe11.png)

(there's no `h1` element either which is [also an issue](https://dequeuniversity.com/rules/axe/4.1/page-has-heading-one) 👀

**Comment by sanz17** [comment]
hello @carolstran could you pls assign me the issue. I would like to work on it
