### ISSUE TITLE
Tooltip component is deprecated in Blueprint

### ISSUE THREAD

**Issue by mikeesto** [electron/fiddle#1095]
The Tooltip component has been deprecated in Blueprint in favour of Tooltip2.

Old Tooltip component with deprecation message: https://blueprintjs.com/docs/#core/components/tooltip
New Tooltip2 component: https://blueprintjs.com/docs/#popover2-package/tooltip2

Components that use Tooltip in fiddle:

- [settings-electron.tsx](https://github.com/electron/fiddle/blob/main/src/renderer/components/settings-electron.tsx)
- [version-select.tsx](https://github.com/electron/fiddle/blob/main/src/renderer/components/version-select.tsx)

**Comment by erickzhao** [comment]
related: https://github.com/electron/fiddle/issues/1045
