### ISSUE TITLE
[refactor]: improve electron versions `not downloaded` option

### ISSUE THREAD

**Issue by BlackHole1** [electron/fiddle#1097]
@BlackHole1 OK, so I realized I didn't have the "Not downloaded" option checked. Checked that option, and suddenly all the available versions popped up.

Functionally, I'm fine, no more problems. But that wasn't very intuitive for me. I'd suggest separating the "Not downloaded" option, since it's not related to the Stable/Beta/Nightly channels. I'd also suggest having the "Not downloaded" option selected by default if it's not already.

_Originally posted by @craxal in https://github.com/electron/fiddle/issues/1073#issuecomment-1150399810_

**Comment by stoichy** [comment]
Hi! I would like to work on this. 
Where would you suggest to place the "Not downloaded" button? What would be more intuitive, perhaps separating it from the others (Stable/Beta/etc.)?

**Comment by dsanders11** [comment]
@BlackHole1, I believe this was fixed in #1202, so gonna close this as completed. 🙂

**Comment by craxal** [comment]
Confirmed:

![image](https://user-images.githubusercontent.com/3473026/218567018-e333d7e1-8de3-4eeb-a535-c7bce9f9472d.png)
