### ISSUE TITLE
Can't find documentation on controlling the filename for builds? 

### ISSUE THREAD

**Issue by tony-gutierrez** [electron/fiddle#110]
How do I avoid builds like observant-vein-command-1.0.0 Setup.exe? 

Googling didn't get me anywhere?

**Comment by malept** [comment]
Hi, Electron Fiddle is meant to be a starting point to learn about creating Electron apps and the development workflow, not be a full-fledged IDE. The distributable filenames are the default config for Electron Forge makers. If you'd like to change the configuration, we recommend to click "File :arrow_right: Save as Forge Project" and work on your project in the IDE of your choice, the distributable configuration being in the `config.forge` section of the generated `package.json`.

See the [Electron Forge docs](https://v6.electronforge.io/configuration#makers) for details on the configuration options.
