### ISSUE TITLE
GSoC'22 - Proposed methodologies for enabling `contextIsolation`

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1100]
Hey team,
Thanks for having me as a part of GSoC'22 program where I will be refactoring fiddle to latest security standards by enabling `contextIsolation` and thus removing the Node environment from the renderer process.

Here's a high-level description of the project and I will also be listing out the proposed methodologies to tackle the same [(link to my proposal)](https://summerofcode.withgoogle.com/media/user/0235bf11a349/proposal/WkpNcBZ4pIbG2rpy.pdf)

- [x] <b>Migrating away from Parcel bundler</b> - 
This is the preliminary task before starting off with the actual project. In short, the problem arise because parcel requires the Node environment to be present in the the renderer process while bundling any Electron application due to it's HMR configuration.<br/>
<b>Plan -</b>
Hence, I will be removing parcel bundler and add webpack to the Electron forge configuration for the bundling process to take place. I will be following as mentioned in the [docs](https://www.electronforge.io/config/plugins/webpack)!
 
- [x] <b>Moving `ipcRendererManager` to preload scripts</b> - 
As the renderer process is now rid of the Node environment, the event emitter `ipcRenderer` wouldn't be available due to lack of importing Electron modules.<br/>
<b>Plan -</b>
That's why, I will be moving and refactoring the `ipcRenderer` API to preload scripts and it's functions like - `send`/`invoke` will be safely exposed to the renderer process (available using the `window` object)

- [x] <b>Integrating `fiddle-core`</b> - 
Currently, [fiddle-core](https://github.com/electron/fiddle-core) already has the right set of APIs which help to download, manager, bisect and run fiddles. It also provides such [APIs](https://github.com/electron/fiddle-core#api) which can be integrated within fiddle to de-duplicate similar functionalities. Not only this, but issue #644 will also be tackled which will reduce the storage of built electron in the client's machine.<br/>
<b>Plan -</b>
Thus, I will be integrating fiddle-core into fiddle's main process and will call such APIs using the IPC event from the renderer to the main process and back (Basically, an `invoke` call)

- [ ] <b>Refactoring Node calls to `IPC` events</b> -
Finally, the remaining Node APIs have to be refactored as well which are present throughout the renderer process. These Node APIs can be either present in React components OR are used in functions in the renderer process.<br/>
<b>Plan -</b>
The Node APIs will be migrated to the main process and later called using the `invoke` call from the migrated  `ipcRendererManager` present in preload scripts. Here's the rough list having the functions/APIs to migrate - 
  - [x] [For React components](https://gist.github.com/aryanshridhar/0dc9f8cf4e0c202ce1e1b6027928ab46#components).
  - [ ] [Functions in the renderer process](https://gist.github.com/aryanshridhar/0dc9f8cf4e0c202ce1e1b6027928ab46#renderer-modules).
 
<br/>
Hence, I believe that the whole project can be broken down into above listed 4 sub tasks. Also, with each tasks, I will be fixing its jests tests and React tests!<br/><br/>
That's it from my side! Let me know if I missed something or a specific task can be handled properly with better methodology than what is listed.

**Comment by dsanders11** [comment]
Closed by #1453.
