### ISSUE TITLE
Switching versions with an unsaved fiddle shows a confusing dialog

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#112]
### To reproduce:

1. Write some code in one of the code windows.
2. Switch Electron versions using the dropdown.

### What happens:
<img width="516" alt="windows_10" src="https://user-images.githubusercontent.com/172800/48289468-6e94c800-e424-11e8-9b3d-7197c4fa2134.png">

### What I expect to happen:
Switch versions without changing any of my code.

**Comment by nornagon** [comment]
Additionally, "OK" and "Cancel" in that dialog appear to have the same behaviour, which is to say, it doesn't change the code.

**Comment by erickzhao** [comment]
I believe this one has been resolved. Will close.
