### ISSUE TITLE
[bug] showMe->electron APIs->DesktopCapture not work on electron 19.0.6

### ISSUE THREAD

**Issue by terry2010** [electron/fiddle#1121]
![图片](https://user-images.githubusercontent.com/1849037/175857443-6fb7cac9-06c4-4846-893c-2da54e428a78.png)

desktopCapturer move to main process since 17.0.0

**Comment by BlackHole1** [comment]
It looks like we need to re-engineer the architecture of `Show Me` 🤔
Make it work: insert the correct code according to the different electron versions.

**Comment by erickzhao** [comment]
@BlackHole1 I think something might be interesting is to fetch the data from `electron/electron` `docs/fiddles` contents which is versioned by default
