### ISSUE TITLE
Gist URL box complains about perfectly valid URL

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#113]
<img width="379" alt="electron_fiddle" src="https://user-images.githubusercontent.com/172800/48653918-78d33b00-e9bd-11e8-9803-b8fd540e7a6d.png">

I triggered this state by first pasting something invalid into the box (anything that isn't a gist URL will do). After that, the input box ceases to function.

**Comment by felixrieseberg** [comment]
Fixed with https://github.com/electron/fiddle/commit/2acc7112b7a94e4158e144e5c6e19ea270bcd8e4
