### ISSUE TITLE
Redo doesn't work

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#1131]
**Version:** Version 0.29.1 (17.4.1)

To repro:

1. type some stuff
2. undo it (Cmd+Z or edit menu)
3. try to redo it (Cmd+Shift+Z or edit menu)

### Expected behavior
Undone edits are redone

### Actual behavior
Nothing happens

**Comment by codebytere** [comment]
Is this on macOS? I can't repro this with the provided steps - Cmd+Z and then Cmd+Shift+Z works just as expected 🤔
