### ISSUE TITLE
Ask to confirm before closing app and loosing data

### ISSUE THREAD

**Issue by bpasero** [electron/fiddle#1142]
I was spending quite some time on writing a fiddle and then went over to publish as Gist. Here I was greeted with an error, so I opened settings and updated by GitHub access token.

Then I was thinking that the X button top keft closes settings (assuming this was another window on top of the fiddle window), but in fact it was closing the entire app and all my changes were lost.

![image](https://user-images.githubusercontent.com/900690/182381755-5422340b-b621-44af-8248-18492452adc5.png)

**Ideally:**
* set the window to document edited (macOS) when the user makes any input
* ask to confirm before closing the window or app (all OS)
* best: restore the contents after restart?

**Comment by kunal-iitj** [comment]
can I pick this issue. I am a beginner to open source. I have done some work in react and node though.

**Comment by erickzhao** [comment]
Hey @kunal-iitj feel free. PRs are always welcome.

**Comment by BhinbahadurUK** [comment]
Go for it all permission granted

UK Bhinbahadur

**Comment by harshcut** [comment]
I feel like opening a confirmation dialog on every close would be quite annoying. Maybe there is a better solution?

**Comment by dsanders11** [comment]
I think this is a bug, as this behavior already exists - Fiddle will ask if you want to exit if it's unsaved.

It looks like the bug is that it loses state that it is unsaved on a publish error. If the publish was successful it wouldn't be considered unsaved so it wouldn't prompt you before exiting.
