### ISSUE TITLE
Can't scroll down in version-select dropdown

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1154]
Just noticed that I am unable to scroll further down in version select dropdown to view all the electron versions though I have marked them to be visible in the settings.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53977614/183342400-2043cf21-e31d-44f8-b942-005d355ade1a.gif)

Might be related to #1146 
cc @BlackHole1

**Comment by BlackHole1** [comment]
Hmmm. A bit strange, I think it has something to do with react-window, @codebytere  what do you think?
