### ISSUE TITLE
File dialog overwrites the file manager's "Show hidden files" setting in Linux/GNOME

### ISSUE THREAD

**Issue by akilan27** [electron/fiddle#1163]
Steps to Reproduce:

  - Go to Files (Nautilus) and make sure you can see hidden files (dotfiles) by checking the checkbox under Hamburger Menu -> Show Hidden Files.
   - Go to Fiddle
   - From menu choose File -> Open...
   - Open a file or click cancel.
   - Go to Files (Nautilus). You can no longer see hidden files. The checkbox under Hamburger Menu -> Show Hidden Files is now unchecked.

Ideally, Fiddle's file dialog should respect user's settings for Nautilus/desktop manager and not override them.

I think this is actually a bug in Electron but that issue seems dead now: https://github.com/electron/electron/issues/34706 

Thanks for looking into this.

**Comment by erickzhao** [comment]
Since this seems to be a general Electron issue rather than a Fiddle-specific bug, I'd track the issue upstream and close this one. I don't think there's anything actionable for this repository aside from bumping the Electron version if there's a fix available.

**Comment by BlackHole1** [comment]
See: https://github.com/electron/electron/issues/34706#issuecomment-1216053784

I will take the time to fix this recently 😃

**Comment by BlackHole1** [comment]
@akilan27 I have just fixed the bug and I will submit a PR in the next two days

**Comment by akilan27** [comment]
Thank you.
