### ISSUE TITLE
Editors list does not scroll - items cut off when there are too many files

### ISSUE THREAD

**Issue by thewheat** [electron/fiddle#1187]
When there are too files added, it can cause the top/bottom of the Editors list to get cut off as the section does not seeem to scroll (found while trying to test https://github.com/electron/fiddle/issues/690)

<img width="322" alt="image" src="https://user-images.githubusercontent.com/892961/194761450-90f18405-6144-44e7-aff4-b7f8c1c72c06.png">

Toggling Console can get the top bit to show but now the files at the bottom get cut off
<img width="543" alt="image" src="https://user-images.githubusercontent.com/892961/194761514-af006a44-1de2-4491-b779-8dd889ac2f8c.png">

* * *

Looks like there is an `overflow: hidden` causing this
<img width="1606" alt="image" src="https://user-images.githubusercontent.com/892961/194761570-5f2e9b0e-c99f-4bc7-9c1e-32631f2ddfa3.png">

We can set `overflow: auto` but scrollbar styling is not there
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/892961/194761626-fda5ab4b-820a-426d-892b-898e73a36bfa.png">

**Comment by BlackHole1** [comment]
@thewheat Would you be interested in submitting a PR for this?

**Comment by thewheat** [comment]
Sure I'll try give it a go! Haven't dealt with the UI side of things so may take a bit of digging to get that scrollbar design in
