### ISSUE TITLE
Migrate `fiddle-core` to main process

### ISSUE THREAD

**Issue by aryanshridhar** [electron/fiddle#1203]
Covers the major part of code migration of Node API to the renderer process.

`IPC.INITIALIZE_FIDDLE`- Initialize the fiddle core in main process.
`IPC.RUN_FIDDLE`- IPC event to run fiddle.
`IPC.STOP_FIDDLE`- IPC event to stop the running fiddle.

**Comment by aryanshridhar** [comment]
(Will create separate pr for better coder review/git history)

**Comment by dsanders11** [comment]
Closed by #1452.
