### ISSUE TITLE
Nothing happens when clicking "Run"

### ISSUE THREAD

**Issue by edu-stx** [electron/fiddle#1216]
I've recently installed Fiddle and clicked on "Open in Fiddle" from [electron's Introduction docs](https://www.electronjs.org/docs/latest/#running-examples-with-electron-fiddle). 

Fiddle opened correctly and loaded the code. I installed electron 21.3.3 and 22.0.0. However, regardless of which version is selected, nothing happens when I click "Run". The console displays the following,

```
Saving files to temp directory...
Saved files to /tmp/tmp-70425-RwBWr7dRxs9N
```

And that's it. After seeing these messages in the console, nothing happens. No window pops up and there are no further messages in the console.

Using Ubuntu 22.04 LTS

**Comment by edu-stx** [comment]
After closing the app and opening it again, it now works. There seems to be a bug where if opened for the first time using a link, it doesn't work. Maye the setup tour interferes with running the app for the first time?

Now that it's running, feel free to close this issue.

**Comment by dsanders11** [comment]
May be related to #1217. Going to close this as suggested, but if you find a repro for what you were seeing, please share. 👍
