### ISSUE TITLE
Action Button Stuck on "Checking status" After Downloading Version

### ISSUE THREAD

**Issue by dsanders11** [electron/fiddle#1238]
**Steps to Reproduce:**

1. Go to Settings -> Electron
2. Click "Download" next to an Electron version and wait for it to finish downloading
3. Close Settings
4. Observe that the action button is now stuck in "Checking status" state
5. Changing the version on the selector dropdown gets the button back to a normal state

**Comment by ckerr** [comment]
From settings, we should be calling fiddle-core's [`installer.ensureDownloaded()`](https://github.com/electron/fiddle-core/blob/main/src/installer.ts#L302) instead of `installer.install()`
