### ISSUE TITLE
BUG: New debs of Electron Fiddle are made with tar.zst (need to revert to ubuntu-20.04 or ubuntu-18.04)

### ISSUE THREAD

**Issue by theofficialgman** [electron/fiddle#1244]
ubuntu-latest is now ubuntu 22.04

ubuntu has an extension to apt that uses tar.zst to compress file in debs. this is used by default by dpkg when packaging debs in 22.04

this prevents all debs from installing on debian/raspbian

you need to switch to building with ubuntu-20.04 or ubuntu-18.04 which do not use this functionality when packaging debs

https://github.com/Botspot/pi-apps/actions/runs/3971114611/jobs/6807621730#step:4:939

**Comment by theofficialgman** [comment]
alternativly you can specify the compression method as gzip through a dpkg command like option, debhelper override, or whatever method you use to build these debs

**Comment by mitesh-raval** [comment]
Workaround :

Follow the steps in the following link for repackaging as tar.xz (replacing the other .deb name for electron-fiddle~.deb) : 

https://gist.github.com/goproslowyo/fe95c8e07c73593e2099687eeda78bc5

I just did this on my chromebook linux (Debian 11) and I was able to install electron-fiddle successfully.
