### ISSUE TITLE
Prevent selection of text in title bar buttons.

### ISSUE THREAD

**Issue by GGIEnrike** [electron/fiddle#1247]

**Comment by jkleinsc** [comment]
@GGIEnrike your comment was deleted as a violation of [the Electron Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md). You may consider this an official warning.

Please do not interact with the project for 24 hours. After that, please look through your open issues and edit them to ensure they're entirely on-topic, and we can continue the discussion here about the best way to go forward.
