### ISSUE TITLE
Failed to spawn Fiddle

### ISSUE THREAD

**Issue by jixian01** [electron/fiddle#1264]
Hello,
i just downloaded the fiddle for windows 64 und want to try the example in https://www.electronjs.org/docs/latest/.
but if i click run in fiddle the error or warning shown on console
Failed to spawn Fiddle: Unrecognized electron name: "23.0.0"

Thanks!

**Comment by dsanders11** [comment]
Hi @jixian01. This is a known issue, see #1241. Closing and opening Fiddle again will fix it.

**Comment by jixian01** [comment]
@dsanders11 Thank you! did try and works now.

**Comment by dsanders11** [comment]
@jixian01, great! Sorry about the bug, we'll hopefully get it fixed soon.
