### ISSUE TITLE
all circle CI runs are failing with "Failed to fetch config.yml file."

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#1290]
Examples: [1](https://app.circleci.com/pipelines/github/electron/fiddle/476), [2](https://app.circleci.com/pipelines/github/electron/fiddle/481), [3](https://app.circleci.com/pipelines/github/electron/fiddle/474).

Possibly fixed by @VerteDinde's https://github.com/electron/fiddle/pull/1276?

**Comment by erickzhao** [comment]
We had to enable CircleCI on the GitHub repo to work on the #1276 migration PR, but since that isn't done then I think these failures are expected.

**Comment by ckerr** [comment]
Makes sense. Feel free to close since it's a known issue, or to leave open if you want something to track it

**Comment by a6uxa4** [comment]
fuck you

**Comment by a6uxa4** [comment]
i help you free but behind money

**Comment by VerteDinde** [comment]
@ckerr The CircleCI PR is up for review now! I'll close this when that PR is merged 🙂

**Comment by dsanders11** [comment]
Closed by #1276. 🎉
