### ISSUE TITLE
Show Welcome Tour stuck app.

### ISSUE THREAD

**Issue by HashimotoYT** [electron/fiddle#133]
## Version

* Fiddle: 0.4.0
* Operating system: Microsoft Windows [Version 10.0.18298.1000]

## Steps to Reproduce

0. **(I do not advise. Reproduced in screencast)** Modify fiddle.
1. Open `Show Welcome Tour` dialog
2. Click `Show me around`
3. Click `Continue`

### Expected Behavior

All works fine and welcome tour continued.

### Actual Behavior

App stucks.

## Screencast of reproducing

![repo](https://user-images.githubusercontent.com/24681191/50318564-91f26e80-04ca-11e9-990d-b84006f4716f.gif)

/cc @felixrieseberg

**Comment by codebytere** [comment]
Happens on MacOS as well, same repro steps

**Comment by felixrieseberg** [comment]
Ugh, damn. I can repro and will fix this.
