### ISSUE TITLE
[MacOS] [ARM64] Blank screen

### ISSUE THREAD

**Issue by RightFS** [electron/fiddle#1357]
I'm a new user of fiddle, it's my first time to run this app, and it shows me a blank screen.

* Blank screen
* No response on menu item like `prefrences`

<img width="1468" alt="image" src="https://github.com/electron/fiddle/assets/12915306/5d48dbdb-1892-402d-9299-3aaeae79f53e">

**Comment by codebytere** [comment]
@RightFS if you click Help in the top menu item, then `Show Developer Tools`:

<img width="494" alt="Screenshot 2023-05-15 at 12 45 43 PM" src="https://github.com/electron/fiddle/assets/2036040/32b8dba4-3b9d-41fd-891d-5c57183a319e">

What do you see in the console? Is there an error?

**Comment by zpinocchio** [comment]
I got same error, by open Dev tools, it show me that:
Uncaught Error: Corrupted version data
    at t.getDefaultVersion (index.js:2:4078294)
    at new t.AppState (index.js:2:4051960)
    at new t.App (index.js:2:3929855)
    at index.js:2:4113606
    at index.js:2:4113636
    at index.js:2:4113640

![image](https://github.com/electron/fiddle/assets/49098424/d82e544c-73f0-414e-bc6f-2e1872713a83)

soft info:
Electron Fiddle
0.35.1
© Electron Authors
https://github.com/electron/fiddle/graphs/contributors
