### ISSUE TITLE
Cannot install, Windows indetifies Fiddle as malware

### ISSUE THREAD

**Issue by KingDanx** [electron/fiddle#1415]
Windows 10 Version: 22H2 
OS build: 19045.3208

![image](https://github.com/electron/fiddle/assets/88867180/73bb69bb-8454-4387-8b58-2a45ab4f48a7)
![image](https://github.com/electron/fiddle/assets/88867180/42197785-38bd-44f4-9d7b-e22a488b49f0)
![image](https://github.com/electron/fiddle/assets/88867180/7e86b2cd-1248-438a-9f8d-551546b44584)

**Comment by DavidDurlach** [comment]
I just received an identical error to the red "Malicious File" screen capture above 2023-07-28:
Edition	Windows 11 Pro
Version	22H2
Installed on	‎2/‎16/‎2023
OS build	22621.1992
Experience	Windows Feature Experience Pack 1000.22644.1000.0

**Comment by dsanders11** [comment]
Thanks for the reports. The long story short is the Windows releases accidentally stopped getting code signed after 0.32.1 as a result of changing our release process, and it wasn't immediately apparent. Windows has recently gotten more aggressive complaining about unsigned executables, which is what is being seen in this issue.

We've resolved the issue and will be putting out a new release, 0.34.0, next week which should close this issue. 👍
