### ISSUE TITLE
iframe element is not showing in dom tree and memory tab.

### ISSUE THREAD

**Issue by gzspark** [electron/fiddle#1449]
[Gist](https://gist.github.com/gzspark/f3d5e83bb61a559356a9ce8767992ca6)

When calling the createIFrame() function from the console, the iframe page is displayed, but it does not appear in the DOM tree. 

<img width="1669" alt="截屏2023-08-23 18 09 23" src="https://github.com/electron/fiddle/assets/142960561/a5f83de5-a96d-4e07-b050-b45cbac236cc">

In the memory panel, it is also not displayed, and the memory value is incorrect. This page in Chrome is approximately 90MB.

<img width="1539" alt="截屏2023-08-23 18 17 58" src="https://github.com/electron/fiddle/assets/142960561/ce7a1d9a-2e4b-4436-b199-6e8c6c54beb9">

**Comment by dsanders11** [comment]
This is the wrong repo for this issue. If you think this is a bug in Electron, please create an issue on [the `electron/electron` repo](https://github.com/electron/electron).
