### ISSUE TITLE
Commands Runner trapped at "Unzipping" after spawn failure

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#1468]
It's possible for Fiddle to end up in a bad commands runner state if the Fiddle fails to spawn in some cases. If this happens, the runner button can get stuck in an infinite "Unzipping" spin which can't be changed.

Example Causal Error:

> Failed to spawn Fiddle: Error invoking remote method 'START_FIDDLE': Error: EPERM: operation not permitted, unlink 'C:\Users\codebytere\AppData\Roaming\Electron Fiddle\electron-bin\current\d3dcompiler_47.dll'

<img width="583" alt="Screenshot 2023-09-26 at 12 23 39 PM" src="https://github.com/electron/fiddle/assets/2036040/490e7ea3-9997-4a8e-9e0a-acb27ef5aca3">

**Comment by dsanders11** [comment]
I think we may want to address this upstream in `fiddle-core`. It sets the state to `installing` when it starts installing but doesn't handle the possibility of an error occurring which should reset the state. Probably want to wrap the code in this area in a `try/catch` and reset the state to `downloaded` if an error happens.

https://github.com/electron/fiddle-core/blob/a8fee08371043568b07b88e3b6078555f3384b96/src/installer.ts#L379-L404

**Comment by dsanders11** [comment]
Upstream PR to address this and the other issues where the state gets stuck in downloading (does not address any underlying issues with downloading): https://github.com/electron/fiddle-core/pull/90
