### ISSUE TITLE
Electron Fiddle Never Stops Downloading

### ISSUE THREAD

**Issue by gayatri-kadam** [electron/fiddle#1469]
The downloading process goes on forever without any error in windows 10.

![image](https://github.com/electron/fiddle/assets/32020314/90a4067d-da93-49e6-8580-c61c7809dfc0)

**Comment by markwylde** [comment]
For me, (macOS M2), it never even starts:
<img width="1492" alt="Screenshot 2023-11-03 at 18 28 03" src="https://github.com/electron/fiddle/assets/5929807/de7918f8-c85b-475b-8ad4-968815f4ab12">

**Comment by dsanders11** [comment]
I think this might be fixed in v0.34.5, so I'm going to close this for now. If you still run into it on that version, feel free to ping me and I'll reopen.
