### ISSUE TITLE
Fiddle fails to launch Electron process on Linux

### ISSUE THREAD

**Issue by aiddya** [electron/fiddle#1470]
Fiddle 0.34.2 fails to launch Electron process on Linux. I've tested it on both Fedora (RPM package) and Ubuntu 22.04 (Debian package).

Fiddle's console output and the symbolicated crash are attached.

[console_output.txt](https://github.com/electron/fiddle/files/12745099/console_output.txt)
[symbolicated_crash.txt](https://github.com/electron/fiddle/files/12745100/symbolicated_crash.txt)

**Comment by fdciabdul** [comment]
Same problem here

![image](https://github.com/electron/fiddle/assets/31664438/d64da934-04e0-4686-bcc0-19ccc4f43b01)

**Comment by dsanders11** [comment]
@aiddya, this is fixed in [the v0.34.3 release](https://github.com/electron/fiddle/releases/tag/v0.34.3)

**Comment by aiddya** [comment]
Confirmed that it's fixed. Thanks!
