### ISSUE TITLE
Missing Windows Releases for v0.34.3

### ISSUE THREAD

**Issue by gateshifter** [electron/fiddle#1478]
Hello. Not sure if the Windows releases are supposed to be available at this moment, but the links are and they result in a 404. The links on the main page are also pointing to 404s. 

https://github.com/electron/fiddle/releases/download/v0.34.3/

Best

**Comment by ravindusha** [comment]
Same with macOS. Both links in [this page](https://www.electronjs.org/fiddle) for macOS are dead links.

**Comment by BlackHole1** [comment]
It seems that only Linux builds are available at https://github.com/electron/fiddle/releases/tag/v0.34.3, missing the Windows and MacOS versions.

PTAL @dsanders11

**Comment by dsanders11** [comment]
v0.34.3 is a Linux-only release while we migrate code signing certificates for Windows and macOS.
