### ISSUE TITLE
Windows installer certificate revoked.

### ISSUE THREAD

**Issue by Flightkick** [electron/fiddle#1488]
Looks like the code signing certificate for the installer has been revoked.

![image](https://github.com/electron/fiddle/assets/8693699/00a0698a-9b42-48d8-bcaa-153f7dfd6a8a)

Possibly related to https://github.com/electron/fiddle/issues/1478#issuecomment-1759081793

**Comment by Nakus0426** [comment]
I have encountered the same problem, which has caused me to be unable to install it now.

**Comment by dsanders11** [comment]
We are currently migrating our code signing certificates for Fiddle to ones provided by OpenJS Foundation, and it took a bit longer than anticipated unfortunately. We'll try to get a new Windows release out with the new certificate ASAP.

**Comment by dsanders11** [comment]
This should be fixed in the v0.34.5 release: https://github.com/electron/fiddle/releases/tag/v0.34.5

As such I'm going to close this issue as fixed. Thank you for your patience. 👍
