### ISSUE TITLE
Infrastructure: Replace electron-download, improve download experience

### ISSUE THREAD

**Issue by felixrieseberg** [electron/fiddle#149]
We're currently using `electron-download`. This has benefits: We're now that we're always downloading the "right" Electron binary and can simply pull in its latest version to get the same behavior as `npm i electron`.

But it also has downsides:
 * `electron-download` constantly prints to stdout, creating quite a bit of unnecessary work when used as a library
 * It comes with dependencies that need resources but end up not benefiting the user experience
 * We currently can't get the progress of the download

We should either improve `electron-download` to the point where it can be properly used as a library or replace it entirely. Improving is probably the better path but it might require splitting `electron-download` into multiple packages.

cc @MarshallOfSound

**Comment by malept** [comment]
> Improving is probably the better path but it might require splitting `electron-download` into multiple packages.

I'm interested in hearing what you think about what the new packages would be.

**Comment by felixrieseberg** [comment]
@malept I'd love a module that simply handles the download (or maybe even just getting correct url to use), which could then be consumed by `electron-download` (with shell UI & co).

**Comment by malept** [comment]
> I'd love a module that simply handles the download _[...]_, which could then be consumed by `electron-download` (with shell UI & co)

It sounds like a simple `electron-download-core` :arrow_right: `electron-download` split to me. I was already thinking of replacing `nugget` with `got` + `progress` (or whatever progress bar module is in vogue right now), this would abstract it further.

**Comment by MarshallOfSound** [comment]
@malept @felixrieseberg I've rewritten `electron-download` a few times (and once with `got`) and I can never reach feature parity (especially things like proxy support).  Not sure if that should be a massive concern but it's quite hard to match that proxy stuff

**Comment by malept** [comment]
I think that once we resolve https://github.com/electron/get/pull/148, we can (finally) start working on this issue.

I'm interested to hear what folks think about how we should show download progress.

**Comment by erickzhao** [comment]
@malept Would probably be ideal to show progress using a Blueprint.js component in the Version Select right where the "Downloading" text is right now. As well, allow the download to be cancelled by hovering and clicking on the same area.

**Comment by malept** [comment]
> As well, allow the download to be cancelled by hovering and clicking on the same area.

I'll need to think about how we can expose download cancellation so we can resolve #320. It seems problematic with the current implementation because we're using stream piping to write the HTTP response to a file.

**Comment by erickzhao** [comment]
Closed in https://github.com/electron/fiddle/pull/358, I believe.

We now use `@electron/get` and have a progress bar in our downloads.
