### ISSUE TITLE
Show Me -> Shell Demo not working

### ISSUE THREAD

**Issue by SpoonOfDoom** [electron/fiddle#1490]
Hi,
I'm new to Electron and just discovered the fiddle. I was messing around with the "Show Me" examples a bit, and I noticed that the Shell example does not work. It appears that the `const { shell } = require('electron')` in preload.js does not work, as `shell` stays `undefined`:

> [54160:1026/192215.651:INFO:CONSOLE(6)] "Uncaught TypeError: Cannot read properties of undefined (reading 'openExternal')", source: file:///C:/Users/chris/AppData/Local/Temp/electron-fiddle-2100-702yucriB41o/index.html (6)

I've tried this with the latest minor versions of Electron 25, 26 and 27, and all had the same behaviour.

Now as I said, I'm new to this, so I'm not 100% sure if this is a broken example, or if it actually should work as is and there is some other problem.

**Comment by codebytere** [comment]
hey @SpoonOfDoom - this happened as a result of a sandbox default change in Electron 20. I've opened a PR to fix it.

**Comment by SpoonOfDoom** [comment]
Got it, thanks for the reply (and the fix, of course)!
