### ISSUE TITLE
Broken Darwin downloads

### ISSUE THREAD

**Issue by mxschmitt** [electron/fiddle#1503]
Repro:

1. Navigate to https://www.electronjs.org/fiddle
2. Click on Download on darwin-arm64

It ends up using 

https://github.com/electron/fiddle/releases/download/0.34.5/Electron.Fiddle-darwin-arm64-0.34.5.zip

which is a 404 but it should use:

https://github.com/electron/fiddle/releases/download/v0.34.5/Electron.Fiddle-darwin-arm64-0.34.5.zip

(missing v version prefix)

**Comment by mxschmitt** [comment]
Probably caused by https://github.com/electron/website/commit/c41589bce35c65e28459b4ab5515f408dc387a4c.

cc @dsanders11

**Comment by dsanders11** [comment]
Thanks!
