### ISSUE TITLE
Error launching app | Electron exited with signal SIGTERM. | Electron exited with code 3489660927.

### ISSUE THREAD

**Issue by lopezvoliver** [electron/fiddle#1515]
I added the following code to the template electron fiddle in `main.js` ([complete gist available here](https://gist.github.com/lopezvoliver/951784c060cd22bba0ef9d4c29019874)) to investigate an [issue I am having developing an extension in vscode](https://github.com/microsoft/vscode/issues/199492): 

```js
  var XmlHttpRequest = require("xmlhttprequest").XMLHttpRequest;
  xmlHttp = new XmlHttpRequest();
  try{
  xmlHttp.open("GET", "", false);
  xmlHttp.send(""); 
  console.log(xmlHttp.responseText); // Should return undefined
  }catch(err){
    console.log(err);
  }
```

Note that the above code works when running through node and the expected output is:

```bash
$ node testXmlHttpRequest.js 
undefined
```

In electron fiddle (0.34.5 in Windows; Electron v27.0.4), the app fails to launch with the following error (pasting as image below, as the text can't be copied from the popup).
 
![image](https://github.com/electron/fiddle/assets/14804652/8831f9ef-d67d-4581-98dc-5102b05535f0)

The error message starts with "Error launching app" and then complains about being Unable to find Electron app at `C:\Users\myusername\AppData\Local\Temp\electron\electron-fiddle-randomString\` and the following seems to be [this code from the xmlhttprequest library](https://github.com/driverdan/node-XMLHttpRequest/blob/master/lib/XMLHttpRequest.js#L483C66-L483C66)

In the console, there is no error message, except for either "Electron exited with signal SIGTERM." or "Electron exited with code 3489660927.". 

Is this a bug in `electron/fiddle` or `electron/electron`, or am I missing something?  As I am testing using fiddle, I am submitting the issue here, but I suspect it might be from electron.

**Comment by dsanders11** [comment]
> Is this a bug in `electron/fiddle` or `electron/electron`, or am I missing something? As I am testing using fiddle, I am submitting the issue here, but I suspect it might be from electron.

It's not a bug in either. You can rule out Fiddle by saving the fiddle to disk and running it directly with Electron and see the same result (via `yarn start`, for example).

The library you're using, `xmlhttprequest`, is the problem. It tries to spawn a new Node.js process and pass code as a string, which isn't going to work with Electron and leads to the error you see. Refs https://github.com/driverdan/node-XMLHttpRequest/blob/97966e4ca1c9f2cc5574d8775cbdacebfec75455/lib/XMLHttpRequest.js#L483-L507

**Comment by lopezvoliver** [comment]
How would one go about "catching" the error then? and why does the same code work "as is" in node?

**Comment by dsanders11** [comment]
You can't catch the error, the error is coming from a separate process which is being spawned and failing to start. It works in Node.js because the module was designed for Node.js and is intending to spawn Node.js with the `-e` option, an option which Electron does not support.

**Comment by lopezvoliver** [comment]
Thanks @dsanders11 , I finally understood what you meant: the issue is that `process.argv[0]` when launched from electron  points to `./node_modules/electron/dist/electron`, so it is the equivalent of attempting to do:

```bash
~/testElectron$ ./node_modules/electron/dist/electron -e "console.log('hey')"
Error launching app
Unable to find Electron app at /home/lopezom/testElectron/console.log('hey')

Cannot find module '/home/lopezom/testElectron/console.log('hey')'
Require stack:
- /home/lopezom/testElectron/node_modules/electron/dist/resources/default_app.asar/main.js
- 
```
