### ISSUE TITLE
Support upcoming Electron 5.0 with nodeIntegration disabled by default

### ISSUE THREAD

**Issue by miniak** [electron/fiddle#157]
Electron 5.0 is going to have `nodeIntegration` disabled by default (https://github.com/electron/electron/pull/16235).

need to replace
```
mainWindow = new BrowserWindow({width: 800, height: 600})
```
with
```
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: {
    nodeIntegration: true
  }
})
```

**Comment by malept** [comment]
Seems like by default all of the examples should be `nodeIntegration = false`, and maybe there should be a "Show Me :arrow_right: Electron APIs :arrow_right: Node Integration" example.
