### ISSUE TITLE
Editor for preload script

### ISSUE THREAD

**Issue by miniak** [electron/fiddle#159]
Testing `contextIsolation` is currently not possible without a preload script, as the main world does not have access to `require` even if `nodeIntegration` is enabled.

**Comment by MarshallOfSound** [comment]
@miniak You can use `renderer.js` as a preload script and just not include it in the HTML file (that's what I've done in the past)

**Comment by felixrieseberg** [comment]
That's the right solution (for now). I'm closing this until we have a better idea!
