### ISSUE TITLE
Electron Fiddle start fails with segmentation fault

### ISSUE THREAD

**Issue by jabaa** [electron/fiddle#1597]
I can't start Electron Fiddle on Kali Linux. I've installed the .deb package. When I start it with a link or in the GUI, nothing happens. When I start it from terminal, I get a segmentation fault:

```
$ electron-fiddle 
Creating main window
MESA-INTEL: warning: Haswell Vulkan support is incomplete
zsh: segmentation fault  electron-fiddle
```

I've also tried the AppImage package:

```
$ ./Electron.Fiddle-0.36.3-x64.AppImage 
MESA-INTEL: warning: Haswell Vulkan support is incomplete
Creating main window
zsh: segmentation fault  ./Electron.Fiddle-0.36.3-x64.AppImage
```

I don't see, how I could debug the problem. What could be the reason?

**Comment by jabaa** [comment]
Same problem with a fresh Debian 12.5

**Comment by jabaa** [comment]
I've installed libglib2.0-bin and reinstalled electron-fiddle. Now, it seems to work on Debian. I wasn't able to test on Kali.

**Comment by nitinsdg** [comment]
I am also getting same issue of segmentation fault in ubuntu 22, below is error message. Any help is appreciated.

Creating main window
MESA-INTEL: warning: Haswell Vulkan support is incomplete
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
Segmentation fault (core dumped)

**Comment by jabaa** [comment]
@codebytere What and where is the main script? `electron-fiddle` looks like a compiled binary.

**Comment by aadcg** [comment]
> Could you please attach a crash dump to help us get more information? You can collect them by adding the following snippet to your main process code, before `app.whenReady`:
> 
> ```js
> const { app, crashReporter } = require('electron')
> console.log(app.getPath('crashDumps'))
> crashReporter.start({ submitURL: '', uploadToServer: false })
> ```
> 
> Then reproduce the crash, zip up the crash dumps directory and attach it here. Thanks!

Running a fiddle with `main.js` populated as you instruct above outputs the following. The files at `/tmp/...` are gone.

```log
Saving files to temp directory...
Saved files to /tmp/electron-fiddle-68331-MHLGpjIpctpO
Electron v29.4.0 started.
LaunchProcess: failed to execvp:
/home/aadcg/.config/Electron
[69076:0525/174237.585693:FATAL:zygote_host_impl_linux.cc(202)] Check failed: . : Invalid argument (22)

Electron exited with signal SIGTRAP.
```

**Comment by jabaa** [comment]
I'm not sure if my issue was unclear. I can't even start the program `electron-fiddle`. The IDE doesn't open. I'm not talking about running a fiddle.

**Comment by aadcg** [comment]
@jabaa it is clear to me. I would like to request re-opening #1598.

**Comment by jabaa** [comment]
But I think it's unclear to @codebytere. How can I add a JavaScript code snippet if I can't even start the program?

**Comment by aadcg** [comment]
@jabaa I can run Electron applications, but I can't run fiddles.

**Comment by jabaa** [comment]
@aadcg You can start `electron-fiddle` and we can't. That are two different, probably unrelated problems. If you want to re-open the other issue, you should answer the question there, asked two days ago.

**Comment by dsanders11** [comment]
Hi @jabaa, can you test the latest release ([v0.36.4](https://github.com/electron/fiddle/releases/tag/v0.36.4)) and see if this is still a problem for you? Thanks!

**Comment by jabaa** [comment]
@dsanders11 It seems to work now. Thank you.
