### ISSUE TITLE
SIGTRAP error on Ubuntu

### ISSUE THREAD

**Issue by aadcg** [electron/fiddle#1598]
Installed via `.deb`. The first error is easily fixed by following the instructions provided but I'm clueless about the second. Any idea? Thanks.

```
Console ready 🔬
Saving files to temp directory...
Saved files to /tmp/electron-fiddle-62593-op2n7hSFKe4p
Electron v29.4.0 started.
[62731:0524/190011.842919:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/aadcg/.config/Electron Fiddle/electron-bin/current/chrome-sandbox is owned by root and has mode 4755.

Electron exited with signal SIGTRAP.
Saving files to temp directory...
Saved files to /tmp/electron-fiddle-62593-EsSoCyyD6GLQ
Electron v29.4.0 started.
LaunchProcess: failed to execvp:
/home/aadcg/.config/Electron
[62772:0524/190051.235193:FATAL:zygote_host_impl_linux.cc(202)] Check failed: . : Invalid argument (22)

Electron exited with signal SIGTRAP.
```

**Comment by codebytere** [comment]
Duplicate of https://github.com/electron/fiddle/issues/1597

**Comment by aadcg** [comment]
I have doubts whether this issue is a duplicate of #1597, since I am reporting that I can't run any fiddle while the other issue mentions not being able to run `electron-fiddle`.

**Comment by erickzhao** [comment]
Hey @aadcg, are you able to run https://github.com/electron/electron-quick-start outside of the context of Fiddle? That's the sample code that we load by default into the program.

**Comment by aadcg** [comment]
> Hey @aadcg, are you able to run https://github.com/electron/electron-quick-start outside of the context of Fiddle? That's the sample code that we load by default into the program.

Yes, I am. That's why it is even more intriguing to me.

**Comment by dsanders11** [comment]
Hi @aadcg, can you test the latest release ([v0.36.4](https://github.com/electron/fiddle/releases/tag/v0.36.4)) and see if this is still a problem for you? Thanks!

**Comment by aadcg** [comment]
@dsanders11 I figured the issue yesterday. It's unrelated to Electron. It's due to bwrap and a very odd Ubuntu policy. See the details [here](https://github.com/containers/bubblewrap/issues/505#issuecomment-2093203129). To fix it, I disabled the `apparmor` service.

**Comment by loicm** [comment]
@aadcg I stopped `apparmor` (`sudo service apparmor stop`), then ran my fiddle code but I still have the same error.

I use Electron Fiddle 0.36.4

Any idea how to make it works? Thanks!

**Comment by rruggiero** [comment]
This issue has been ongoing with the ubuntu release for so long now and there is not resolution that I can identify form constant searching.  I come back to this ubuntu release every 4-5 months to check that it has been resolved and it hasn't for over a year now.

Uninstalling it and reinstalling it different ways doesn't help.  Maybe something is broken in my ubuntu config, who knows?

**Comment by Kicey** [comment]
> [@dsanders11](https://github.com/dsanders11) I figured the issue yesterday. It's unrelated to Electron. It's due to bwrap and a very odd Ubuntu policy. See the details [here](https://github.com/containers/bubblewrap/issues/505#issuecomment-2093203129). To fix it, I disabled the `apparmor` service.

Can you write the specific solution, please. It's really important to those who learn electron and use linux desktop. There's not any detailed solution for this on the whole internet.

**Comment by Kicey** [comment]
> [@aadcg](https://github.com/aadcg) I stopped `apparmor` (`sudo service apparmor stop`), then ran my fiddle code but I still have the same error.
> 
> I use Electron Fiddle 0.36.4 on Ubuntu 24.04
> 
> Any idea how to make it works? Thanks!

This's a same problem as https://github.com/electron/electron/issues/42510 .

In short, you can execute the `sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0` to solve the problem. But there is a security risk in it. So just use this in you developing environment, and set the variable back by executing `sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1`.

There is a more elegant but a little complex solution, write an apparmor profile to allow the electron-fiddle's using of userns privilege. Maybe I'll post it later.

**Comment by Kicey** [comment]
> > [@aadcg](https://github.com/aadcg) I stopped `apparmor` (`sudo service apparmor stop`), then ran my fiddle code but I still have the same error.
> > I use Electron Fiddle 0.36.4 on Ubuntu 24.04
> > Any idea how to make it works? Thanks!
> 
> This's a same problem as [electron/electron#42510](https://github.com/electron/electron/issues/42510) .
> 
> In short, you can execute the `sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0` to solve the problem. But there is a security risk in it. So just use this in you developing environment, and set the variable back by executing `sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=1`.
> 
> There is a more elegant but a little complex solution, write an apparmor profile to allow the electron-fiddle's using of userns privilege. Maybe I'll post it later.

We need to grant the privilege to the executable by create an apparmor profile to solve the problem, execute the following commands (sudo needed):
```bash
echo 'abi <abi/4.0>,
include <tunables/global>
profile fiddle-electron /home/'$USER'/.config/Electron\ Fiddle/electron-bin/current/electron flags=(unconfined) {
    userns,
}' > /etc/apparmor.d/fiddle-electron

apparmor_parser -r /etc/apparmor.d/fiddle-electron

systemctl reload apparmor
```
