### ISSUE TITLE
arm64 deb will crash when opened

### ISSUE THREAD

**Issue by UniverseOfTomorrow** [electron/fiddle#1599]
When I open it on an arm64 machine it closes suddenly

**Comment by UniverseOfTomorrow** [comment]
the cpu  is  HUAWEI Kirin 9006C @ 3.13GHz

**Comment by dsanders11** [comment]
Hi @UniverseOfTomorrow, can you test the latest release ([v0.36.4](https://github.com/electron/fiddle/releases/tag/v0.36.4)) and see if this is still a problem for you? Thanks!

**Comment by codebytere** [comment]
Closing as I believe this to have been addressed - please let us know if you're still seeing issues and we can re-open it!
