### ISSUE TITLE
failing while make installers for fiddle

### ISSUE THREAD

**Issue by soumalya01** [electron/fiddle#186]
Hi 
for my system the Make installer step is failing. Please find the debug log attached.
[npm-debug.log](https://github.com/electron/fiddle/files/3062463/npm-debug.log)

let me know if any further information is required.
- Soumalya

**Comment by malept** [comment]
Can you please provide a Fiddle saved as a GitHub gist that exhibits this behavior? Also, any information about the Linux system that you're running (distribution, architecture, etc.) so that we can try to reproduce the problem.

**Comment by soumalya01** [comment]
Hi, I'm new to electron js, downloaded electron fiddle and it's the default program that opens the first time that is having the issue. The program works fine if I run it or do Package Fiddle from it . Only the Make Installer is failing. 

PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
Node - v8.10.0
npm - 3.5.2

**Comment by malept** [comment]
What version of Fiddle is this?

**Comment by soumalya01** [comment]
I've tried with 5.0.0 beta 7 and also 4.1.4 ... same in both

**Comment by malept** [comment]
Sorry, I should have been clearer. That's the *Electron* version you're running your Fiddle with. The *Electron Fiddle* version is ... well, I guess you can't find the Electron Fiddle version in the app? That's a problem, I'll raise an issue.

Anyway, I found the bug. The version of Electron Forge that's being used to create installers is rather out of date.

**Comment by soumalya01** [comment]
what can I do to fix that ?

**Comment by malept** [comment]
The workaround is to export it as a Forge project, and then use your package manager (e.g., NPM or yarn) to upgrade the Electron Forge dependencies.

Otherwise, you'll need to wait for a new release of Electron Fiddle.

**Comment by soumalya01** [comment]
I want to have my project compiled into .deb(linux) or .exe (windows). Will I be able to do that from the Forge project ?

**Comment by malept** [comment]
Yes. Just run `npm run make` (or `yarn make`, if you use Yarn). Read about how to configure your Electron Forge project at the Forge v6 website: https://v6.electronforge.io/

**Comment by soumalya01** [comment]
"The version of Electron Forge that's being used to create installers is rather out of date." - so even if I run "npm run make" that will make use of the same electron forge and is failing. Will I be able to update the electron forge and continue with the project ? 

Can I have older version of NodeJS / NPM that would work with the current version of electron forge ?

**Comment by malept** [comment]
> Will I be able to update the electron forge and continue with the project ?

As I said in an earlier comment:

> use your package manager (e.g., NPM or yarn) to upgrade the Electron Forge dependencies.

If you don't know how to do this, consult the documentation for your package manager.

> Can I have older version of NodeJS / NPM that would work with the current version of electron forge ?

Electron Forge currently works with Node 6 and above. Soon (within the next month, I imagine), it will require Node 8 or above, because Node 6 will no longer be supported by the Node.js team as of the end of April.
