### ISSUE TITLE
Add an about dialog

### ISSUE THREAD

**Issue by malept** [electron/fiddle#188]
As far as I can tell, there's no way to figure out what version of Electron Fiddle a user is running without asking them to dig into the source code of the bundled app, or if they're on Linux, using their package manager. Including this will make it easier to troubleshoot GitHub issues.

**Comment by Saoskia** [comment]
What OS are you using? I'm on a Mac, and there already exists an About dialog by clicking on the app name and selecting 'About Electron Fiddle'. I don't have access to other OS to check them.

![Screen Shot 2019-05-27 1](https://user-images.githubusercontent.com/18042873/58420806-a36f2080-80d1-11e9-852a-3ab82ec0d467.png)
![Screen Shot 2019-05-27 2](https://user-images.githubusercontent.com/18042873/58420814-a833d480-80d1-11e9-8974-64740dbc0af6.png)

**Comment by codebytere** [comment]
@Saoskia the issue is that it's not showing what version of _Electron_ is used in a given version of Fiddle, not what version of _Fiddle itself _is being used!

**Comment by Saoskia** [comment]
@codebytere My apologises, that's not what I understood the issue to be.
