### ISSUE TITLE
Update to Electron v4.2.0

### ISSUE THREAD

**Issue by miniak** [electron/fiddle#194]
This fix landed in Electron v4.2.0, which removes some DLLs, which were not supposed to be shipped with Electron:
https://github.com/electron/electron/pull/18060

It will decrease the Windows installer size by 3 MBs.

**Comment by malept** [comment]
I believe Felix is planning on upgrading to Electron 5 soonish.

**Comment by felixrieseberg** [comment]
This is now done, thank you 🙇
