### ISSUE TITLE
Feature Request: Add ability to clear console output

### ISSUE THREAD

**Issue by miniak** [electron/fiddle#196]
It would be really useful to allow clearing the console output by:
- adding a button to the toolbar (next to the "Console" button)
- adding a context menu item (below "Run Fiddle" for example)

**Comment by alectrocute** [comment]
Sorry it's unrelated, but if anybody googling how to clear Electron's dev console in Node and instead stumbles across this (like I did), here's how:

```js
const readline = require('readline')
const blank = '\n'.repeat(process.stdout.rows)
console.log(blank)
readline.cursorTo(process.stdout, 0, 0)
readline.clearScreenDown(process.stdout)
```
