### ISSUE TITLE
"Run" doesn't work

### ISSUE THREAD

**Issue by Makrophago** [electron/fiddle#208]
I installed Electron Fiddle with the deb package (v0.7.0) on Debian 10. When I try to run the "Hello World" example, the console shows this output, and nothing else happens :

> Saving files to temp directory...
Saved files to /tmp/tmp-23491RpVKD4JFRUR0
Electron v5.0.0-beta.7 started.
Electron exited.

**Comment by malept** [comment]
Does it work if you select Electron 4.2.4 instead of 5.0.0-beta.7?

**Comment by Makrophago** [comment]
Okay it works with Electron 4.2.4, sorry for the useless issue.

Thank you !
