### ISSUE TITLE
Spacing issues with <code> tags in tour

### ISSUE THREAD

**Issue by kerolloz** [electron/fiddle#235]
![image](https://user-images.githubusercontent.com/36763164/61381734-c9cc6380-a8ab-11e9-817f-5a67847a4f4b.png)

this should be `calls BrowserWindow`

**Comment by kerolloz** [comment]
I also found this
![image](https://user-images.githubusercontent.com/36763164/61382467-20866d00-a8ad-11e9-82af-61c4b5c3c2bb.png)

**Comment by kerolloz** [comment]
After inspecting the source code, I believe this is an issue with `<code>` tags. 
![image](https://user-images.githubusercontent.com/36763164/61382537-40b62c00-a8ad-11e9-9337-e60f0e73063f.png)
![image](https://user-images.githubusercontent.com/36763164/61382563-4e6bb180-a8ad-11e9-8853-0ef1300430a8.png)

**Comment by kerolloz** [comment]
I'm providing more info...
OS: Linux, Ubuntu 19.04.
Fiddle Versison:  v0.9.0

**Comment by malept** [comment]
Seems like https://github.com/electron/fiddle/pull/216 didn't fix it?

**Comment by erickzhao** [comment]
I think #216 didn't work here because the HTML parser does not detect spaces at the beginning of the line as a whitespace character. If it did, indenting would be hard (each line actually has like 12 spaces in front of it 😅).

This will not work:
```html
<p>
  Every Electron app starts with a main script, very similar to how
  a Node.js application is started. The main script runs in the "main
  process". To display a user interface, the main process creates renderer
  processes – usually in the form of windows, which Electron calls 
   <code>BrowserWindow</code>.
</p>
```

but this should:
```html
<p>
  Every Electron app starts with a main script, very similar to how
  a Node.js application is started. The main script runs in the "main
  process". To display a user interface, the main process creates renderer
  processes – usually in the form of windows, which Electron
  calls <code>BrowserWindow</code>.
</p>
```

@kerolloz if you'd like to take this up, this should be an easy problem to fix!

**Comment by malept** [comment]
There's also the classic/old-school "use `&nbsp;`" solution.

**Comment by kerolloz** [comment]
@erickzhao 

Okay, I'll fix it

**Comment by arnitkun** [comment]
I have a pull request ready but am unable to push my fix.

I have 2FA and use SSH instead of HTTPS.

**Comment by erickzhao** [comment]
Hi @arnitkun, you would want to fork the repository first, since your account does not have push access for `electron/fiddle`.

For more details: https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

**Comment by arnitkun** [comment]
yeah, sorry I forgot I can do that.
