### ISSUE TITLE
Can't install on Windows 7

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#237]
This happens when I try to run the installer (both the 32-bit and 64-bit installers produce the same error):
<img width="503" alt="Cursor_and_Windows_7" src="https://user-images.githubusercontent.com/172800/61656948-a839f600-ac76-11e9-8232-b41402bd4a52.png">

**Comment by malept** [comment]
Huh. Is that a Squirrel problem?

**Comment by MarshallOfSound** [comment]
You're running a scarily outdated version of Windows 7 😆 https://github.com/Squirrel/Squirrel.Windows/issues/1512#issuecomment-509041129

**Comment by nornagon** [comment]
Yikes, okay thanks!
