### ISSUE TITLE
Introduce a bisect helper

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/fiddle#244]
This might be a bit of a big project but I have a _terrible_ local script I use nowadays to effectively "git bisect" but for electron nightly releases.  The idea being to track down when something broke using our new nightly releases.

Chromium has a similar thing --> https://www.chromium.org/developers/bisect-builds-py

If fiddle had a "bisect" helper where you could give a start nightly and an end nightly and go through the bisect logic to narrow down which release broke it that would be _awesome_.

I'm imagining a UI where you choose two nightly releases and then two new "good" and "bad" buttons appear which you click until you've finished bisecting

**Comment by erickzhao** [comment]
+1 on this! Seems like a useful feature for anyone trying to debug in `electron/electron`. As for UX, how do you feel about this? (Don't mind the crude prototyping 😅)
![image](https://user-images.githubusercontent.com/16010076/62330893-ec937600-b46e-11e9-8626-fe8205690adb.png)

I also think this feature should be hidden by default, as it would confuse people simply trying to use Fiddle as a playground to test out Electron APIs.

cc @MarshallOfSound @felixrieseberg

**Comment by MarshallOfSound** [comment]
> Downloads all versions between range

The beauty of bisecting is we shouldn't have to do that, we should download versions on demand.  bisect is like searching a sorted binary tree.  I'd suggest reading up https://git-scm.com/docs/git-bisect

Instead of "next version" as a button there should probably be a "Good Version" button and "Bad Version" button because we need to know which way to continue the search.

> I also think this feature should be hidden by default,

I agree, hidden somewhere in the options would be good, or just a menu item with a shortcut "Cmd+Shift+B" 🤷‍♂
