### ISSUE TITLE
Removing an active Electron version has unexpected behaviour

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#245]
Repro:
1. Go to Electron Settings in Preferences.
2. Delete your active versions.

For local version: reverts to latest nightly (regardless if nightlies are enabled or not)

For downloaded version: the version selector will still stay on the deleted one and infinitely hang on the `Checking Status` state.

**Comment by akgupta0777** [comment]
Close this issue you cannot remove active versions now.

**Comment by Slapbox** [comment]
After upgrading from an older version that supported `13.x.x` to the newest version of Electron Fiddle, which supports a minimum of `14.0.0-beta.`, we are stuck on "Checking status" indefinitely no matter what we try so far.

@felixrieseberg

**Comment by Slapbox** [comment]
Scratch that. We tried **Delete All Downloads** and it did nothing to fix the issue. Then we restarted Electron Fiddle and used **Delete All Downloads** a second time, then restarted again, and it resolved the issue.

**Comment by erickzhao** [comment]
@Slapbox you can enable obsolete versions in the settings as well (sorry for unintuitive UX)

![image](https://user-images.githubusercontent.com/16010076/159587315-77a9945e-b95f-46ba-8085-4d791f4aeaa2.png)
