### ISSUE TITLE
Cancelling overwrite when opening new Fiddle does not cancel local file path change

### ISSUE THREAD

**Issue by 8R90** [electron/fiddle#251]
Ok, first time posting an issue on GitHub so bear with me.

Lets say you want to switch fiddle from Fiddle1 to Fiddle2 but you have unsaved changes on Fiddle1.
You will get a dialog box asking:
"Opening this fiddle will replace your unsaved changes. Do you want to proceed?"
With options: Cancel and Yes

If you cancel the dialog box the code will stay the same (Fiddle1) but the path will change to the project you were about to open (Fiddle2).
So if you Ctrl-S at this point you will overwrite the code in Fiddle2 with the code of Fiddle1.

- - -

Fiddle version: 0.9.0
Windows 10

**Comment by erickzhao** [comment]
Thanks for the report @8R90! I can take a look into fixing this.

Note: this bug occurs as well when cancelling remote loading from a Gist, a Fiddle protocol, or a Show-Me.
