### ISSUE TITLE
Is there a way to run fiddle behind a proxy?

### ISSUE THREAD

**Issue by a1994846931931** [electron/fiddle#258]
Hi, I'm new to electron and fiddle. My fiddle app is blocked in downloading electron, which seems to be an issue of the company proxy. I checked the preference but failed to find any setting related to the proxy.
I can't proceed anymore without the downloading finished. Yet I wonder if there is still a way to set a proxy for the whole app?

**Comment by Dec-F** [comment]
The download is implemented by the `electron-download` package, you can go to the readme of this package.
Simply put, you only need to declare `ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/`in `.npmrc`

**Comment by clark-97** [comment]
I use windows 10 20H2, and add `ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"` in "C:\Users\%username%\.npmrc", but do not work. which specific `.npmrc` need to declare `ELECTRON_MIRROR` @fhyoga

**Comment by clark-97** [comment]
on https://github.com/electron/fiddle/issues/149#issuecomment-735930520 @erickzhao said
> Closed in #358, I believe.
> 
> We now use `@electron/get` and have a progress bar in our downloads.


Is there any way to speed up the download now? I have already spent an hour, only half of the electron V12.0.1 was download.

<img width="210" alt="Snipaste_2021-03-23_14-17-21" src="https://user-images.githubusercontent.com/66821547/112101955-7c58db80-8be2-11eb-809e-11748c4f1100.png">

**Comment by winterssy** [comment]
I have found the solution, instead of declaring `ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/"` in `.npmrc`, just set the system environment variable of `ELECTRON_MIRROR` to `https://npm.taobao.org/mirrors/electron/`, it works. See: https://www.electronjs.org/docs/tutorial/installation#mirror

**Comment by rambo-panda** [comment]
mac and oh-my-fish

```bash
env ELECTRON_MIRROR="https://npm.taobao.org/mirrors/electron/" open /Applications/Electron\ Fiddle.app
```

**Comment by temberature** [comment]
SHASUMS256.txt may be broken, mannul download solve my problem

macOS

**Comment by BlackHole1** [comment]
> SHASUMS256.txt may be broken, manual download it solve my problem
> 
> macOS

@temberature See: https://github.com/electron/fiddle/pull/1159
