### ISSUE TITLE
Fiddle doesn't launch when Windows in dark mode

### ISSUE THREAD

**Issue by vhashimotoo** [electron/fiddle#260]
### Version & OS

OS: Windows 10 1903

### Steps to reproduce the behavior

1. Set Windows into dark mode
2. Try to open fiddle.

### Expected behavior

Fiddle opens.

### Actual behavior

Fiddle don't open.

### Additional context

After setting to light it's works.
Possible related to https://github.com/electron/electron/issues/19468.

**Comment by erickzhao** [comment]
According to https://github.com/electron/electron/issues/19468#issuecomment-697184273, it seems like this issue is resolved upstream with newer versions of Electron. I'll test later today on my Windows machine.

**Comment by faiwer** [comment]
> Version & OS
> OS: Windows 10 1903

The same issue is on Mac with a dark mode. Chip: M1 Pro.
