### ISSUE TITLE
Docs Fiddle unable to load when Fiddle is already running

### ISSUE THREAD

**Issue by vhashimotoo** [electron/fiddle#261]
### Version & OS

OS: Windows 10 1903
Fiddle: v0.10.0

### Steps to reproduce the behavior

1. Run fiddle
2. Try to launch fiddle from docs (example: https://fiddle.electronjs.org/launch?target=electron/main/docs/fiddles/screen/fit-screen).

### Expected behavior

Fiddle successfully load gist and ask if needed to replace the current state.

### Actual behavior

Fiddle window flashes and closed.

**Comment by dsanders11** [comment]
This seems to work now, other than the issue in #1007. I'm gonna close this since it mostly works.
