### ISSUE TITLE
Infobox for launch from documentation, not informative

### ISSUE THREAD

**Issue by HashimotoYT** [electron/fiddle#262]
The formulation of this message it's not great for new users or not only for new.

> Are you sure you sure

😂. Yes I'm sure

> `example from the Electron docs`?

Here I'm planning to see the name of the example that launched, it gives some confidence it's really that what's user want.

> from fiddle path 'v7.0.0-beta.4'?

Maybe `this "name of fiddle" for Electron v7.0.0-beta.4`?

---

The Picture of the Box:

![2019-10-10 (1)](https://user-images.githubusercontent.com/24681191/66605178-3c519480-ebb8-11e9-93bd-84777c61ee2f.png)

**Comment by felixrieseberg** [comment]
That's an obvious bug _and_ a good idea. I'll make a PR!
