### ISSUE TITLE
Electron won't run due to wrong permissions -- FATAL:setuid_sandbox_host

### ISSUE THREAD

**Issue by jacobq** [electron/fiddle#268]
When I try to download an electron version and run any app (just tried with default code) I get an error message when I click "Run":

```
Saving files to temp directory...
Saved files to /tmp/tmp-17980JATmV7lLyLvJ
Electron v8.0.0-beta.1 started.
[18095:1030/113527.965989:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/me/.config/Electron Fiddle/electron-bin/8.0.0-beta.1/chrome-sandbox is owned by root and has mode 4755.
Electron exited.
```

I'm used to seeing this error message on my local electron projects the first time I install the `electron` module (when working in Linux) and usually work-around it by running a simple script:

```bash
# fix-permissions.sh
ELECTRON_MODULE_DIR=./node_modules/electron
sudo chown root.root $ELECTRON_MODULE_DIR/dist/chrome-sandbox
sudo chmod 4755 $ELECTRON_MODULE_DIR/dist/chrome-sandbox
```

Don't others run into this? If not, why not? If so, perhaps it's something that `fiddle` could automatically correct?

* `node -v` --> v12.13.0
* `npm -v` --> 6.12.0
* `electron-fiddle` --> Installed from `electron-fiddle_0.10.0_amd64.deb`
* `uname -a` --> "Linux (my hostname) 5.2.0-3-amd64 # 1 SMP Debian 5.2.17-1 (2019-09-26) x86_64 GNU/Linux"

Related to https://github.com/electron/electron/issues/17972

**Comment by jacobq** [comment]
For some reason, the permission change I mentioned does seems to resolve this when using electron-fiddle. However, when I first run `sudo sysctl kernel.unprivileged_userns_clone=1` as suggested [here](https://github.com/electron/electron/issues/17972#issuecomment-486927073) then things seem to work fine.

**Comment by Kicey** [comment]
New to fiddle. I've run into this today.
