### ISSUE TITLE
I can't install Electron in China.

### ISSUE THREAD

**Issue by LOVELIBERTY1314** [electron/fiddle#270]
![image](https://user-images.githubusercontent.com/35516695/68037668-348e9700-fd03-11e9-8a52-f083d8fd888c.png)
My network is running well. But I can't install Electron in China. How should I do to solve this problem.

**Comment by chaostheory** [comment]
This is probably a question for your ISP or organization.

**Comment by g8up** [comment]
Does Electron Fiddler support network proxy?
