### ISSUE TITLE
Show Me > Electron APIs > Dialogs not working

### ISSUE THREAD

**Issue by lainz** [electron/fiddle#274]
The file is not open in the window.

I fixed it like this:

```
  dialog.showOpenDialog({
    title: 'Hello!',
    properties: ['openFile']
  }).then(file => {
    mainWindow.loadURL(`file://${file.filePaths[0]}`)
  })
```

**Comment by erickzhao** [comment]
Hey @lainz, thanks for the report. This has already been fixed in a previous PR: https://github.com/electron/fiddle/pull/272

that has yet to be published in a new release.

**Comment by lainz** [comment]
Ok thanks.
