### ISSUE TITLE
isDevMode should be called in main/devtools.ts

### ISSUE THREAD

**Issue by Letra312** [electron/fiddle#276]
isDevMode is of function type but used as boolean.

**Comment by erickzhao** [comment]
Hey @Letra312, thanks for the report! How come you closed PR #275?

**Comment by Letra312** [comment]
Oh, I'm an open source newcomer. I saw the merge was blocked so I closed it.
I've opened it again.

**Comment by erickzhao** [comment]
No worries! Merging is blocked for all of our PRs until there's at least one approving review. 🙂

**Comment by Letra312** [comment]
@erickzhao Thanks!
I've fixed them in my master branch and reopened another PR #277 .
Hope that's not a fault. 🤦‍♂️

**Comment by Letra312** [comment]
Coverage decreased again...
I'll figure it out.

**Comment by Letra312** [comment]
Here comes a `catch (error)`, and I need to add a test case.😂

https://github.com/electron/fiddle/blob/c052686de4de03fecf6e6584831fda5e65d3e563/src/main/devtools.ts#L24-L26
