### ISSUE TITLE
Update existing Fiddle gist when publishing with non-empty URL field

### ISSUE THREAD

**Issue by tessus** [electron/fiddle#290]
After I publish a gist and change something and click `Publish` again, a new gist is created.

The gist should be updated instead (new revision). A new gist should only be created, iff the fiddle url address field is empty.

Maybe this is a crazy idea, but IMO a lot more intuitive as it is now.

**Comment by deadcoder0904** [comment]
Would also love to have a toast notification when a Gist is Published. Currently, only URL changes, but an alert is much better for UX
