### ISSUE TITLE
"Run Fiddle..." fails to run Fiddle on Ubuntu 16.04

### ISSUE THREAD

**Issue by jcorks** [electron/fiddle#295]
### Issue Details
* **Fiddle Version:**
electron-fiddle_0.12.0_amd64
* **Electron Version:**
7.1.8 (as reported by /usr/lib/electron-fiddle/version)
* **Operating System:**
Ubuntu 16.04 

### Expected Behavior
Pressing the "Run" button (or F5 accel, or through the menu) for the provided sample should run the application.

### Actual Behavior
Nothing opens. More specifically in the console display, electron seems to save temporary files and attempt to run, then exits with no display. Example output:
```
Saving files to temp directory...
Saved files to /tmp/tmp-21097WQyRaPSLAc9N
Electron v7.1.4 started.
Electron exited.
```
Note that this is after setting the proper `root` user/group and `4755` bits for `chrome-sandbox`.
When enabling advanced logging, I get a new line in between starting and exiting:
```
LaunchProcess: failed to execvp: /home/user/.config/Electron
```
This is a fresh install, so everything is default except the enabling of advanced logging. This behavior is consistent across all the client Electron versions I've tried, namely 7.1.8, 7.1.9, and 7.1.4.

**Comment by malept** [comment]
Does this happen if you try to use the [`electron-quick-start` repository](https://github.com/electron/electron-quick-start) as well? If so, can you try deleting `~/.config/Electron` and try again?

**Comment by jcorks** [comment]
After setting the proper bits and user/group for `chrome-sandbox`, `electron-quick-start` works without issue. As a note though, there was no `~/.config/Electron` specifically.

**Comment by ckerr** [comment]
FWIW when I install `electron-fiddle_0.12.0_amd64.deb` and try running electron 7.1.4, it works for me on Ubuntu 19.10. I tried both with and without an `~/.config/Electron` directory and it worked both ways.

It's possible there's something odd about 16.04. I don't have that handy at the moment.

`LaunchProcess: failed to execvp` seems to come from `base/process/launch_posix.cc`, as if `LaunchProess()` were called with only `~/.config/Electron`. I don't know what's causing that, and I haven't been able to reproduce it, but it smells like a valid bug to me

**Comment by malept** [comment]
I created a Xubuntu 16.04/amd64 VM, loaded Fiddle 0.12.0 on it (the same file as Charles), and the default Fiddle ran successfully for me.
