### ISSUE TITLE
shortcuts for view > zoom don't work

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#296]
As demoed by Andy in the training sessions :smile:

**Comment by erickzhao** [comment]
Did a little digging, seems like this is an outstanding bug from Electron 3 (link to issue: https://github.com/electron/electron/issues/15496).

A workaround that's promising is manually adding an accelerator, although the shortcut displayed will be off (link to workaround: https://github.com/electron/electron/issues/15496#issuecomment-450685872).

**Comment by codebytere** [comment]
@ckerr it does work, but owing to shifting needs lost in translation you need to do `Cmd+Shift+Plus" for zoom in

**Comment by bavulapati** [comment]
Can the shortcut for zoomIn be changed to `Cmd + equals` instead of `Cmd + Plus` ?
Noticed this usage by Visual studio code

**Comment by codebytere** [comment]
This works in latest release of Fiddle - closing out.
