### ISSUE TITLE
Add ability to reset default editor view

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#297]
Although we have a drag-and-drop interface that allows you to re-arrange the editors as much as possible. However, it's kind of a struggle to reset your arrangement if you misclick or whatnot.

It would be cool to add a button that programmatically sets the arrangement in the react-mosaic library to the `DEFAULT_MOSAIC_ARRANGEMENT` constant.

**Comment by kimberleejohnson** [comment]
Hi, @erickzhao! I chatted with Shelley Vohr yesterday via her Twitter office hours, and she flagged this as a good first open source issue for a junior JavaScript developer with a bit of React experience like me. I've started poking around locally, and I hope to have something to contribute (following the Contributing.MD guidelines) soon. Thank you!

**Comment by erickzhao** [comment]
Hey @kimberleejohnson, that's awesome to hear! Let me know if you have any questions. :)

**Comment by kimberleejohnson** [comment]
Hi, @erickzhao! I took a first pass at this, but I had a few outstanding questions for you here: https://github.com/electron/fiddle/pull/374 

Please let me know if I missed something in the Contributing guidelines, and thank you for your help! 
Kimberlee
