### ISSUE TITLE
Fiddle overwrite warning with ⌘N

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#305]
Right now when you hit the hotkey for New Fiddle (⌘N), it automatically overwrites the existing one that was open. From a user perspective, it is probably cleaner to trigger a similar interstitial confirmation dialog that gets opened when users load in a new fiddle from gist:

<img width="1312" alt="Screen Shot 2020-01-27 at 9 14 20 AM" src="https://user-images.githubusercontent.com/2036040/73197023-7d2cd500-40e5-11ea-91aa-bfd2d9a50277.png">

cc @felixrieseberg @erickzhao what do y'all think? happy to take this if you agree!

**Comment by felixrieseberg** [comment]
Makes perfect sense to me, good idea!

**Comment by codebytere** [comment]
Excited to report that i got myself into a weird state in local dev and you did in fact account for this 🤦‍♀ I don't think there's any new code to write here so i'm just gonna close this out lol
