### ISSUE TITLE
Remember session when re-running fiddle

### ISSUE THREAD

**Issue by davej** [electron/fiddle#313]
I'm testing some stuff involving session and cookies in my fiddle. The session/cookies get wiped out eveytime I run the app and stop it. Is there an option to persist session info?

**Comment by erickzhao** [comment]
Hey @davej, what you're looking for should be under `Settings > Execution > Do not delete user data directores`, if I'm not mistaken.

LMK if that solves the issue!

**Comment by davej** [comment]
Thanks @erickzhao, that solved it :)
