### ISSUE TITLE
Make console searchable

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#317]
📑 As an Electron maintainer, the logs coming from Fiddle's console are useful for debugging purposes.

🔎 Being able to search through these with <kbd>⌘ F</kbd> would be great, especially when advanced Electron logging is enabled in the Chromium settings.

💡 One possible way to approach this would be to refactor the `<Output/>` class into a read-only Monaco editor and pushing new lines of the log through the Monaco Editor APIs.

cc @loc

**Comment by dsanders11** [comment]
@erickzhao, I think this can be closed, since #717 got merged?

**Comment by erickzhao** [comment]
Thank you!
