### ISSUE TITLE
Clicking "esc" in Theme search filter closes the preferences window

### ISSUE THREAD

**Issue by vhashimotoo** [electron/fiddle#322]
Repro:

1. Go to preferences -> general
2. Click the "Choose your theme" box
3. Start searching for something
4. Drop your plans and click "esc" to close this box.

Maybe something for newcomers, just need to disable "esc" when we in the input box.

**Comment by mwoodhousemckenzie** [comment]
:wave: I took a stab at fixing this problem, I am new to OSS contributions so I am not sure if I went about this correctly 😅

**Comment by erickzhao** [comment]
@mwoodhousemckenzie I'll take a look at this tomorrow!
