### ISSUE TITLE
No way to customize the package fiddle.

### ISSUE THREAD

**Issue by chiutse** [electron/fiddle#325]
I am new to electron.
I would like to build a package with customize the app name, author, version, icon, build platform,  extraResources etc...
I have tried to edit the package.json related information. The out come nothing happen to change the app name and author info. The build is depend by folder name and the computer user name.
I have no idea this is the bug or origin design.

**Comment by malept** [comment]
This is by design. From the README:

> Fiddle is not an IDE – it is however an excellent starting point. Once your fiddle has grown up, export it as a project with or without [electron-forge](https://electronforge.io/). Then, use your favorite editor and take on the world!
