### ISSUE TITLE
Could not find npm - electron-fiddle_0.13.1 .deb

### ISSUE THREAD

**Issue by rogeriodeoliveira** [electron/fiddle#365]
Hi! I'm get the same error in "electron-fiddle_0.13.1", it's was fixed in #68 ?

**"Error: Could not find npm. Fiddle requires Node.js and npm to compile packages. Please visit https://nodejs.org to install Node.js and npm."**

```
require('child_process').execSync('which npm').toString()
child_process.js:673 Uncaught Error: Command failed: which npm
    at checkExecSyncError (child_process.js:634)
    at Object.execSync (child_process.js:670)
    at Object.execSync (electron/js2c/asar.js:696)
    at <anonymous>:1:26
```

```
require('child_process').execSync('echo $PATH').toString()
"/home/rogerio/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
"
```
➜  ~ which npm
/home/rogerio/.nvm/versions/node/v10.16.3/bin/npm
```
Running in:  
Linux Mint 19.3 Tricia
node --version v10.16.3
nvm --version 0.35.0

**Comment by Noctua36** [comment]
Same behavior on:

Linux Mint 19.2 Cinnamon
node --version v10.16.3
nvm --version 0.34.0

**Comment by Noctua36** [comment]
It looks like a problem with the use of nvm and the location of the node and npm binaries. The `fix-path` module wont include the path for `/home/gustavo/.nvm/versions/node/v10.16.3/bin/`.

NVM makes use of this script on `~/.bashrc` to dynamically update the $PATH:
```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
```

As a workarround, creating this symlinks solves for me:
```
sudo ln -s $(which node) /usr/bin/
sudo ln -s $(which npm) /usr/bin/
```

**Comment by codebytere** [comment]
Closing as this has been superseded by more recently released versions.

**Comment by daslicht** [comment]
> Closing as this has been superseded by more recently released versions.

how to solve that error ?
