### ISSUE TITLE
Security: follow best practices, maybe update the default fiddle to electron-quick-start?

### ISSUE THREAD

**Issue by Prinzhorn** [electron/fiddle#377]
I just started using Fiddle today after working with Electron for a while. I find it worrying that the default example when you start Fiddle does not follow best-practices and purposely makes the code less secure. Sure it's cool to demonstrate `nodeIntegration` in the `index.html`, but isn't that advanced stuff? Stuff that you should only do once you need to and when you absolutely know what you're doing? (From my experience it is never needed, since you can expose a minimal api via preload).  I must assume many newcomers will first come into contact with Electron via Fiddle and might use the code as a starting point. They might not be aware of the immense implications of `nodeIntegration` and might get comfortable with doing it the wrong way (blindly using Node.js inside renderer, instead of exposing well defined APIs from preload).

Is there a reason Fiddle doesn't just use the same code https://github.com/electron/electron-quick-start does? It looks like a sane starting point, e.g. Node.js integration is disabled and it demonstrates how to safely use Node.js inside preload while still interacting with the page https://github.com/electron/electron-quick-start/blob/d2db0d4cc1f7ebcf6c562eeb5d5e3a8eabd0432e/preload.js

I've searched the issues and haven't seen this come up yet if I haven't missed anything.

**Comment by erickzhao** [comment]
Very good point -- would also probably need to make `preload.js` open by default in that case as well.
