### ISSUE TITLE
Content from Gist won't load if the editor is hidden

### ISSUE THREAD

**Issue by Prinzhorn** [electron/fiddle#387]
1. Load the fiddle (any fiddle with preload.js) https://gist.github.com/Prinzhorn/dfe34f7b9e6e90fbde99f5f20e402747 
2. Click Editors -> preload.js to show the editor
3. It is empty

Now if you load the gist again with the visible preload.js editor it is populated.

This means gists with a preload.js are broken by default, because the preload.js editor is hidden by default.

**Comment by studiochris** [comment]
The same applies to styles and the Stylesheet editor. If the editor is not open, style.css does not load when the fiddle is loaded. Opening the editor after load, style.css is blank. Re-loading the fiddle with the Stylesheet editor open will load style.css and populate the editor.

When running the fiddle without style.css being loaded in the Stylesheet editor, the fiddle has no styles applied, even if the fiddle was saved to a folder or loaded from a gist with style.css included.
