### ISSUE TITLE
"Make installers for Fiddle" task not working

### ISSUE THREAD

**Issue by 0xtrzy** [electron/fiddle#392]
clear instalation
download, run ok
package ok
task->make installers for fidler

------
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'make' ]
2 info using npm@6.14.5
3 info using node@v12.16.1
4 verbose run-script [ 'premake', 'make', 'postmake' ]
5 info lifecycle educated-paste-juggle-tl6gg@1.0.0~premake: educated-paste-juggle-tl6gg@1.0.0
6 info lifecycle educated-paste-juggle-tl6gg@1.0.0~make: educated-paste-juggle-tl6gg@1.0.0
7 verbose lifecycle educated-paste-juggle-tl6gg@1.0.0~make: unsafe-perm in lifecycle true
8 verbose lifecycle educated-paste-juggle-tl6gg@1.0.0~make: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/tmp/tmp-77498s2aclx4nb184/node_modules/.bin:/home/user/.cargo/bin:/home/user/.local/bin:/home/user/bin:/home/user/.cargo/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin
9 verbose lifecycle educated-paste-juggle-tl6gg@1.0.0~make: CWD: /tmp/tmp-77498s2aclx4nb184
10 silly lifecycle educated-paste-juggle-tl6gg@1.0.0~make: Args: [ '-c', 'electron-forge make' ]
11 silly lifecycle educated-paste-juggle-tl6gg@1.0.0~make: Returned: code: 1  signal: null
12 info lifecycle educated-paste-juggle-tl6gg@1.0.0~make: Failed to exec make script
13 verbose stack Error: educated-paste-juggle-tl6gg@1.0.0 make: `electron-forge make`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid educated-paste-juggle-tl6gg@1.0.0
15 verbose cwd /tmp/tmp-77498s2aclx4nb184
16 verbose Linux 5.6.8-300.fc32.x86_64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "make"
18 verbose node v12.16.1
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error educated-paste-juggle-tl6gg@1.0.0 make: `electron-forge make`
22 error Exit status 1
23 error Failed at the educated-paste-juggle-tl6gg@1.0.0 make script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by erickzhao** [comment]
Hey @0xtrzy, I have no trouble running this on macOS. Could you provide more context on your environment? What OS/Fiddle version are you using? Can you reproduce this with the default Fiddle?

**Comment by jeanenchanted** [comment]
same issue with me
