### ISSUE TITLE
Make Save hotkey toggleable

### ISSUE THREAD

**Issue by hoangph271** [electron/fiddle#406]
The Fiddle app behaves almost as fine as a normal text editor/IDE.  
But my hand keep typing ```Ctrl + S``` any time I make a change to my code.  
And it brings up this menu:  
![image](https://user-images.githubusercontent.com/39024711/83490237-dcf31c80-a4d9-11ea-9d09-906192483a83.png)
Pretty annoying, please consider change this behavior

**Comment by erickzhao** [comment]
Hey @hoangph271, thanks for the feedback!

Does this prompt still appear after you have initially saved your Fiddle? That would be a bug, but I'm unable to reproduce on my end (I'm on macOS, though).

On my end, once the Fiddle is saved locally, any subsequent <kbd>⌘</kbd>+<kbd>S</kbd> presses save the files to the directory without prompting the user to show a new save directory.

**Comment by HashimotoYT** [comment]
My feedback: I preferably use Fiddle as an experimental playground when I open and always change the Fiddle and don't want to save them. You always want to use Save hotkey because it's standard and here you always see this dialog what's somehow annoying.

/cc @erickzhao

**Comment by erickzhao** [comment]
Yeah, I see where you're coming from. I don't really save my Fiddles anywhere most of the time, either.

What about an option to make the Save hotkey a no-op for those who are annoyed at it?

**Comment by HashimotoYT** [comment]
Yeah, the setting looks good, but we should leave the saving when we have directory opened for default behavior as they don't annoying and do in the background.

**Comment by hoangph271** [comment]
> Hey @hoangph271, thanks for the feedback!
> 
> Does this prompt still appear after you have initially saved your Fiddle? That would be a bug, but I'm unable to reproduce on my end (I'm on macOS, though).
> 
> On my end, once the Fiddle is saved locally, any subsequent ⌘+S presses save the files to the directory without prompting the user to show a new save directory.
> 
> Alternatively, would you want to be able to bind Save to another hotkey that you don't press instinctively?

---
Yes, sorry for the misleading description.  

The saving option works fine and all files are saved in a directory.  
And this is exactly what I'm talking about: "Alternatively, would you want to be able to bind Save to another hotkey that you don't press instinctively?".  
Thank you.  
As people pointed out, it's not that often that I really want to save the fiddle in a directory.

**Comment by erickzhao** [comment]
Thanks for the clarification! :) 

Will put this on our wishlist for now.

**Comment by k0rn1** [comment]
I would be interested in trying to implement this.

I would add a new point in General Settings called Block Shortcuts including a checkbox for CTRL + S.
Would this be a reasonable way of solving this?

**Comment by erickzhao** [comment]
Hey @k0rn1, that sounds good to me! :)
