### ISSUE TITLE
Update vs publish DX can trip up users

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#412]
Recently fiddle added the ability to update gists when they already exist, such that new fiddles don't get published when one is already working within the app. This is great, but creates a bit of a developer experience trap if someone _does_ want to create a new fiddle after they change code in currently open editors. I ran into this issue today when creating a fiddle for a bug report and then swapping to a new bug - it updated my initial gist and removed my code for the initial bug report. 

Ideally, i'd like to split these two options out - the default I think can/should remain update when a fiddle is already open, but i'd like to retain the option to forcibly publish a new one. If the flow we want to push users toward is to ask them to open a new fiddle every time i do understand that, so in that case we might want to somehow make that clearer to users?

I'm not sure exactly what yall prefer that to look like, but i'm happy to take a stab at it!

**Comment by erickzhao** [comment]
@codebytere I have no immediate suggestions on how to make the flow more functional while keeping clarity, but I think this is a great point.
