### ISSUE TITLE
Only x64 RELEASES and full.nupkg are uploaded to GitHub releases

### ISSUE THREAD

**Issue by mahnunchik** [electron/fiddle#415]
According to current behaviour of GitHub publisher artefacts with the same name doesn't uploaded.

So second `publish` uploads only `*ia32-setup.exe`: https://github.com/electron/fiddle/blob/master/appveyor.yml#L34-L36

Is it expected behaviour?

---

Original question: how to handle both x64 and ia32 `RELEASES/nupkg` uploads?

**Comment by erickzhao** [comment]
We ended up updating the build process and removed the `nupkg` approach entirely. See #504.
