### ISSUE TITLE
Select All Not working inside files

### ISSUE THREAD

**Issue by ProBeta1** [electron/fiddle#434]
Select All option does not selects the entire contents of the file , the shortcut ( Ctrl + A ) works , but the option given in Application Menu doesn't .

## To Reproduce (Linux)
Open Fiddle and tap the Select All sub-menu within the Edit menu.

## Expected behaviour
All content must get selected.

## Actual behaviour
Nothing happens.

**Comment by erickzhao** [comment]
Can also repro on macOS. Thank you for the report!
