### ISSUE TITLE
`electron-default-menu` package uses deprecated app.getName() API

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#441]
When running Fiddle, we get the following warning message, even though we've removed all direct instances of `app.getName()` in the Fiddle code:

```console
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
```

This package we depend on for setting up a default menu in Electron still uses the old API. I've submitted a pull request (https://github.com/carter-thaxton/electron-default-menu/pull/11) to update it, but it's something we should look out for when we eventually upgrade to an Electron version that doesn't support the `app.getName()` API anymore.

**Comment by malept** [comment]
That module hasn't been updated since 2017. We should be prepared to fork or vendor it.

**Comment by carter-thaxton** [comment]
New version is published on npm.  Should be good to go.

**Comment by malept** [comment]
@carter-thaxton thanks for the quick response! My comment wasn't personal, I hope you understand where my skepticism was coming from.
