### ISSUE TITLE
Why modules re-install every time I click run?

### ISSUE THREAD

**Issue by Zebraslive** [electron/fiddle#456]
I just want to know how I can prevent it from needing to install modules to temp folders every time I run. It creates a ton of duplicate files on my drive. 
Is this normal? do the temp folders get deleted later automatically?

**Comment by HashimotoYT** [comment]
Fiddle automatically deletes the run folder after a run, it's the reason why the modules reinstall on every run, you can disable the automatically deleting directory in the `File` -> `Preferences` -> `Execution` -> `Do not delete user data directories`.
