### ISSUE TITLE
Clicking 'Restart' in the update dialog does nothing

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#467]
Fiddle notified me that there was an update available this morning, and showed a dialog box with the options "Restart" and "Later". I clicked "Restart", which dismissed the dialog box, but the app did not restart.

Fiddle version: Version 0.15.1 (8.0.2)

**Comment by erickzhao** [comment]
I believe this is an upstream issue (https://github.com/electron/update-electron-app/issues/57). Will leave this open and label it appropriately.
