### ISSUE TITLE
Proplem with Root account

### ISSUE THREAD

**Issue by Barbarosse** [electron/fiddle#468]
Hi I'm using Ubuntu with a root account which is my usual behavior which caused me to have issues with Fiddle.
I start Fiddle with `electron-fiddle  --no-sandbox`, but when I try to run examples from the "Show me" menu I get an error.
I also tried to add `--no-sandbox` in `require('electron')` to become `require('electron --no-sandbox ')` with no success. 

This is the error I get : 

`[61891:0825/130337.256360:FATAL:electron_main_delegate.cc(264)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.

Electron exited.`

**Comment by malept** [comment]
Thanks for filing an issue, but running Electron Fiddle as root is not supported. We're looking into adding documentation to Fiddle to that effect.
