### ISSUE TITLE
Quitting one window with unsaved changes causes all windows to attempt quit

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#469]
Version: 0.15.1 (8.0.2)

To repro:

1. Open Electron Fiddle
2. Open a 2nd window with File -> New Window
3. Make some changes to a file in the new window
4. Click the 'close' button on the new window. The "The current Fiddle is unsaved. Do you want to exit anyway?" dialog will show.
5. Click 'quit'.

What happens:
The new window closes, and then the "The current Fiddle is unsaved. Do you want to exit anyway?" dialog appears in the original window.

What I expect to happen:
The new window should close, but the original window should not show the "Do you want to exit?" dialog.

**Comment by erickzhao** [comment]
@nornagon I just investigated and I think this is fixed in 0.16.0 with #423. Will close for now, but let me know if this pops up again, though.
