### ISSUE TITLE
It should be possible to set a custom Gist description

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#477]
Right now it's hardcoded to 'Electron Fiddle Gist' which is pretty annoying when there are hundreds of them. 

I'll take this one if you all think it's a good idea!

**Comment by erickzhao** [comment]
I'm definitely a 👍  on this.

On a related note, since we use [namor](https://www.npmjs.com/package/namor) to generate the Fiddle app title, we could set the Gist's title to that to at least have some sort of uniqueness to the Gist names even if a custom title is not set,

**Comment by codebytere** [comment]
@erickzhao ooh as a stopgap that sounds great to me for now to set as a default! Wrangling custom descriptions will require some new UI that'll probably require some more thought 🤔
