### ISSUE TITLE
v0.18.0 is a black screen on Windows after fresh install

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#532]
I just installed v0.17.6 and v0.18.0 on a Windows VM. v0.17.6 works as expected, but v0.18.0 is just a menu + a black screen. New dialogs work, e.g. hitting "Open" pops up a new window as you'd expect. But any action taking place in the main window under the menu is swallowed in blackness.

Mac and Linux both run 0.18.0 fine for me; I'm only seeing this on Windows.

![2020-11-20T13:45:19-Screenshot-2919x961](https://user-images.githubusercontent.com/70381/99843431-2b9f7c00-2b37-11eb-97b3-1ee3a42b6a69.png)

**Comment by Moplix** [comment]
I have the same problem,you have found any solustion now?plz

**Comment by erickzhao** [comment]
@Moplix are you encountering this on the latest version (v0.27.0)?

**Comment by Moplix** [comment]
> @Moplix are you encountering this on the latest version (v0.27.0)?
yes,and I can't find any solution.

**Comment by dsanders11** [comment]
My Fiddle just got into this state somehow. Don't know if it is related, but I was doing local development of Fiddle, with `yarn start`, and then switched back to the installed production version, and ran into this.

However, I noticed that it's not stuck on that screen indefinitely, it's just **really** slow. Once it finally loads (10+ seconds later), the UI is also unusably slow, taking 5+ seconds per click.

Can't get DevTools open until it's finally loaded. Did a profile capture of reloading the app while the profiler is loading. It loads a bit faster on the reload, but you can see in the profile that "First Paint" takes 5+ seconds. After the first 1 second there's nothing meaningful shown in the profile until "First Paint" occurs, so it's not clear what is blocking it, or what makes the UI painfully slow after it does load.

GitHub won't let me attach the profile, but I can share it on Slack if anyone thinks they might be able to find anything interesting in it.

@erickzhao @ckerr

**Comment by Moplix** [comment]
> My Fiddle just got into this state somehow. Don't know if it is related, but I was doing local development of Fiddle, with `yarn start`, and then switched back to the installed production version, and ran into this.
> 
> However, I noticed that it's not stuck on that screen indefinitely, it's just **really** slow. Once it finally loads (10+ seconds later), the UI is also unusably slow, taking 5+ seconds per click.
> 
> Can't get DevTools open until it's finally loaded. Did a profile capture of reloading the app while the profiler is loading. It loads a bit faster on the reload, but you can see in the profile that "First Paint" takes 5+ seconds. After the first 1 second there's nothing meaningful shown in the profile until "First Paint" occurs, so it's not clear what is blocking it, or what makes the UI painfully slow after it does load.
> 
> GitHub won't let me attach the profile, but I can share it on Slack if anyone thinks they might be able to find anything interesting in it.
> 
> @erickzhao @ckerr
> 
> EDIT: This may be related to disk stuff. I'd been doing a lot on the machine with Chromium builds and Electron builds, and it was down to only 20 GB free. Chrome and VS Code seemed to be working fine, but I did notice that the search in VS Code had become unusably slow. I freed up space back up to 50 GB, and then restarted the machine, and now Fiddle is back to normal. Interestingly during that fubar state, Task Manager didn't show anything interesting on the disk activity monitor, so it's unclear what was actually in a bad state. Fiddle has a pretty large ASAR (139 MB), so maybe loading everything off disk was being extremely slow due to the disk issues.



> My Fiddle just got into this state somehow. Don't know if it is related, but I was doing local development of Fiddle, with `yarn start`, and then switched back to the installed production version, and ran into this.
> 
> However, I noticed that it's not stuck on that screen indefinitely, it's just **really** slow. Once it finally loads (10+ seconds later), the UI is also unusably slow, taking 5+ seconds per click.
> 
> Can't get DevTools open until it's finally loaded. Did a profile capture of reloading the app while the profiler is loading. It loads a bit faster on the reload, but you can see in the profile that "First Paint" takes 5+ seconds. After the first 1 second there's nothing meaningful shown in the profile until "First Paint" occurs, so it's not clear what is blocking it, or what makes the UI painfully slow after it does load.
> 
> GitHub won't let me attach the profile, but I can share it on Slack if anyone thinks they might be able to find anything interesting in it.
> 
> @erickzhao @ckerr
> 
> EDIT: This may be related to disk stuff. I'd been doing a lot on the machine with Chromium builds and Electron builds, and it was down to only 20 GB free. Chrome and VS Code seemed to be working fine, but I did notice that the search in VS Code had become unusably slow. I freed up space back up to 50 GB, and then restarted the machine, and now Fiddle is back to normal. Interestingly during that fubar state, Task Manager didn't show anything interesting on the disk activity monitor, so it's unclear what was actually in a bad state. Fiddle has a pretty large ASAR (139 MB), so maybe loading everything off disk was being extremely slow due to the disk issues.

ok,I can open the DevTool,and it's show that "Uncaught (in promise) RangeError: Maximum call stack size exceeded",then a number of warnings "DevTools failed to load source map: Could not parse content for file://.....",

**Comment by erickzhao** [comment]
@Moplix @dsanders11 thank you both for the additional debugging information :)
