### ISSUE TITLE
opening developer tools first time messes with background color

### ISSUE THREAD

**Issue by yilmazdurmaz** [electron/fiddle#536]
how to produce:
1- create new fiddle
2- run the fiddle
3- open dev tools and see the background color changes to dark grey as menu bar and dev tools have
4- close and reopen dev tools and see background fixes

version 0.18.0 with electron v11.0.0-beta.20(came with fiddle) , v11.0.2 and v12.0.0-beta.3

ps: seems this happens when background color is not set

**Comment by erickzhao** [comment]
Hey @yilmazdurmaz, does this behaviour also happen to you when running the base `electron-quick-start` repo? http://github.com/electron/electron-quick-start

If so, it'd be out of scope for Fiddle and would be an issue with Electron itself.

**Comment by yilmazdurmaz** [comment]
@erickzhao 
thanks for answering. seems your suspicion is right.  I opened an issue in electron repo, so I close the issue here
