### ISSUE TITLE
Package Problem on Window 10

### ISSUE THREAD

**Issue by JeonghunLee** [electron/fiddle#546]
I download the fiddle here on Window 10 (64bit version)
it's working about Menu-Tasks-Run or Run with Electron APIs  properly but every time I found this problem below when I tried to package it by using Menu-Tasks-Package Fiddle.

Console: 
📦 Packaging current Fiddle...
Saving files to temp directory...
Saved files to C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT
Now running "npm install..."
> core-js@3.8.1 postinstall C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"
[96mThank you for using core-js ([94m https://github.com/zloirock/core-js [96m) for polyfilling JavaScript standard library![0m
[96mThe project needs your help! Please consider supporting of core-js on Open Collective or Patreon: [0m
[96m>[94m https://opencollective.com/core-js [0m
[96m>[94m https://www.patreon.com/zloirock [0m
[96mAlso, the author of core-js ([94m https://github.com/zloirock [96m) is looking for a good job -)[0m
> electron@11.0.4 postinstall C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT\node_modules\electron
> node install.js
added 507 packages from 335 contributors and audited 509 packages in 28.445s
27 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
⚠️ Creating installers failed.. Error encountered:
Error: Command failed: npm run package
- Checking your system
√ Checking your system
[31mIt looks like you are missing some dependencies you need to get Electron running.
Make sure you have git installed and Node.js version >= 10.0.0[39m
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! average-math-forsake-jwhxk@1.0.0 package: `electron-forge package`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the average-math-forsake-jwhxk@1.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\TW08-NT-0486\AppData\Roaming\npm-cache\_logs\2020-12-11T02_03_25_496Z-debug.log

2020-12-11T02_03_25_496Z-debug.log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.14.1
4 verbose run-script [ 'prepackage', 'package', 'postpackage' ]
5 info lifecycle average-math-forsake-jwhxk@1.0.0~prepackage: average-math-forsake-jwhxk@1.0.0
6 info lifecycle average-math-forsake-jwhxk@1.0.0~package: average-math-forsake-jwhxk@1.0.0
7 verbose lifecycle average-math-forsake-jwhxk@1.0.0~package: unsafe-perm in lifecycle true
8 verbose lifecycle average-math-forsake-jwhxk@1.0.0~package: PATH: C:\Users\TW08-NT-0486\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\TW08-NT-0486\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\TW08-NT-0486\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Bandizip\;C:\Users\TW08-NT-0486\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\TW08-NT-0486\AppData\Local\GitHubDesktop\bin;C:\Users\TW08-NT-0486\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\TW08-NT-0486\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\ESTsoft\ALSee\x64
9 verbose lifecycle average-math-forsake-jwhxk@1.0.0~package: CWD: C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT
10 silly lifecycle average-math-forsake-jwhxk@1.0.0~package: Args: [ '/d /s /c', 'electron-forge package' ]
11 silly lifecycle average-math-forsake-jwhxk@1.0.0~package: Returned: code: 1  signal: null
12 info lifecycle average-math-forsake-jwhxk@1.0.0~package: Failed to exec package script
13 verbose stack Error: average-math-forsake-jwhxk@1.0.0 package: `electron-forge package`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\TW08-NT-0486\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:223:5)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\TW08-NT-0486\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:223:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid average-math-forsake-jwhxk@1.0.0
15 verbose cwd C:\Users\TW08-N~1\AppData\Local\Temp\tmp-13420-Ehl3Ql0WHouT
16 verbose Windows_NT 10.0.19041
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package"
18 verbose node v12.14.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error average-math-forsake-jwhxk@1.0.0 package: `electron-forge package`
22 error Exit status 1
23 error Failed at the average-math-forsake-jwhxk@1.0.0 package script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Could you give me advice ?**

**Comment by malept** [comment]
This seems to be the problem

> It looks like you are missing some dependencies you need to get Electron running.
> Make sure you have git installed and Node.js version >= 10.0.0

**Comment by codebytere** [comment]
Closing as solved by https://github.com/electron/fiddle/issues/546#issuecomment-743396781
