### ISSUE TITLE
Loading the fiddle failed: TypeError: Failed to fetch

### ISSUE THREAD

**Issue by mengxianbin** [electron/fiddle#548]
I accessed [the official notification demo - renderer](https://fiddle.electronjs.org/launch?target=electron/v11.0.4/docs/fiddles/features/notifications/renderer) to launch Fiddle,
Fiddle popuped `Are you sure you want to load this 'features/notifications/renderer' example from the Electron docs for version v11.0.4? Only load and run it if you trust the source.`,
I hit `Okay`,
then Fiddle popuped `Loading the fiddle failed: TypeError: Failed to fetch`.

```
Node.js 12.18.3
Chromium 87.0.4280.67
Electron 11.0.4
OS Windows_NT x64 10.0.17763
```

**Comment by asdf-x** [comment]
how to resolve

**Comment by gebilaoman** [comment]
how to resolve
