### ISSUE TITLE
ContextBridge not adding api to window

### ISSUE THREAD

**Issue by willium** [electron/fiddle#550]
See [this fiddle](https://gist.github.com/de26534b1d6a105f3459fb11238f8235)

Getting
```
Uncaught TypeError: Cannot read property 'foo' of undefined
```

**Comment by malept** [comment]
Thanks for filing an issue, but this isn't an issue in Fiddle itself. You should consider using one of the [community forums](https://electronjs.org/community) (including the [Discord community server](https://discord.gg/electron)), as there are more people there available to answer questions.

**Comment by willium** [comment]
Why isn't this an issue with Fiddle?

**Comment by malept** [comment]
When you run your Fiddle, all Electron Fiddle does is execute Electron with your code.

**Comment by willium** [comment]
That makes sense, but this works fine on my local version of Electron and not on Fiddle. It seems like it may be an issue with how Electron bundles `window`?

**Comment by malept** [comment]
Seems like you should configure the browser window to load the preload script.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Discord community server](https://discord.gg/electron).
