### ISSUE TITLE
"Save" dialog goes behind main window when creating new folder

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#551]
To repro:

1. Start a new fiddle
2. Cmd+S
3. Click "New Folder"
4. Click either "Cancel" or "Create"

Expected behavior:
The new folder is created and selected in the save dialog, and the save dialog remains focused

Actual behavior:
The new folder is created and selected, but the save dialog disappears behind the main window. <kbd>Cmd+`</kbd> brings it back.

**Comment by erickzhao** [comment]
Seems like this is an upstream Electron issue with the `createDirectory` option in dialogs that snuck itself in somewhere between Electron 5 and Electron 6.

```js
  dialog.showSaveDialog({
    properties: ['createDirectory'],
  });
```

**Comment by nornagon** [comment]
Ah, is there already a bug on e/e about it?

**Comment by erickzhao** [comment]
Searching the issue tracker for `createDirectory` doesn't yield any results, but I'll file one!

**Comment by erickzhao** [comment]
I've filed an issue upstream and opened a new PR to change the underlying dialog API that we use as a workaround.
