### ISSUE TITLE
Package fiddle not working

### ISSUE THREAD

**Issue by jeanravenclaw** [electron/fiddle#568]
![image](https://user-images.githubusercontent.com/75297066/106385808-21291a80-63e3-11eb-9f73-382cffe837c9.png)
why is this happening?

**Comment by codebytere** [comment]
@jeanenchanted please provide the steps you took prior to encountering this issue. There is no version, no operating system - this issue is insufficient as it stands.

**Comment by jeanenchanted** [comment]
> @jeanenchanted please provide the steps you took prior to encountering this issue. There is no version, no operating system - this issue is insufficient as it stands and we need all of the above to continue or this issue will be closed.

All I did was go to tasks > package fiddle. Version is Electron v11.1.1 on windows 10.  This issue also happens with the default fiddle

**Comment by codebytere** [comment]
@jeanenchanted did you try to rerun when you saw the error? If i leave it it eventually succeeds:

<img width="695" alt="Screen Shot 2021-02-02 at 3 05 06 PM" src="https://user-images.githubusercontent.com/2036040/106674416-0e8c1e00-6568-11eb-95b2-445f09e2585a.png">

**Comment by codebytere** [comment]
Closing as no response provided.
