### ISSUE TITLE
Fiddle not starting intermittently on Windows

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#569]
When i click Run on an arbitrary version, the button remains on "Run" and i see this:

<img width="704" alt="Screen Shot 2021-02-01 at 11 00 32 AM" src="https://user-images.githubusercontent.com/2036040/106505145-be845d00-647c-11eb-82c7-4573e2583ccb.png">

Screenshot from devtools:

<img width="727" alt="Screen Shot 2021-02-01 at 10 59 54 AM" src="https://user-images.githubusercontent.com/2036040/106505162-c3491100-647c-11eb-9949-ce8992c59304.png">

**Comment by vhashimotoo** [comment]
Repro:

1. Run and Stop, again, and again before you even can't open a fiddle.

Another stack trace:

![image](https://user-images.githubusercontent.com/24681191/107159966-65e52080-69a4-11eb-9384-01c8e08c17c5.png)
