### ISSUE TITLE
Feature request: create additional files

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#574]
It would be useful to be able to create files beyond the built-in 5 (main.js, index.html, renderer.js, preload.js and styles.css). e.g. for fiddles which use `<webview>`, it would be convenient to be able to have the webview src point at a 2nd html file. Or for preloads, you might want to have different preloads for two different windows.

**Comment by jkleinsc** [comment]
I'm adding my +1 to this.  I am trying to test service workers in Electron and would love to be able to use fiddle to do so.
