### ISSUE TITLE
x64 Installer not working

### ISSUE THREAD

**Issue by roxymarrese** [electron/fiddle#582]
After installing the 64 bit version of Fiddle, it will run for a bit (enough to get through some of the tour) nd then prompt that there is an update available. Clicking either restart or later will close the application. Then when trying to reopen, it will pop up a message saying the image is valid, but for a different machine type. For the record, my system info states: 64-bit operating system, x64-based processor.

**Comment by erickzhao** [comment]
Might be related to https://github.com/electron/update.electronjs.org/pull/91

**Comment by erickzhao** [comment]
@royal-wisdom could you happen to drop a screenshot or screencap of what's happening?

**Comment by erickzhao** [comment]
I was able to reproduce this on my Windows machine:

![image](https://user-images.githubusercontent.com/16010076/108775777-6dfd9e00-7516-11eb-8911-53c4dd34fa17.png)

**Comment by erickzhao** [comment]
@royal-wisdom Were you installing the latest version (`v0.20.0`) of Electron Fiddle?

As a workaround, could you try:
1) Deleting `%LOCALAPPDATA%\electron-fiddle`
2) Installing the latest release (v0.20.0) from GitHub Releases

**Comment by royal-wisdom** [comment]
> @royal-wisdom Were you installing the latest version (`v0.20.0`) of Electron Fiddle?
> 
> As a workaround, could you try:
> 
> 1. Deleting `%LOCALAPPDATA%\electron-fiddle`
> 2. Installing the latest release (v0.20.0) from GitHub Releases

The version is the v0.20.0, but the 0.19.0 version is also showing up. I don't think that should be an issue though, would it?

Also, thank you for the help and work you have put into figuring this out.

![electron-fiddle](https://user-images.githubusercontent.com/61601347/108895613-cf3e7380-75e1-11eb-8cf4-9043bc2fc63a.PNG)

**Comment by dospolov** [comment]
@erickzhao 0.19 is still in README.MD
![image](https://user-images.githubusercontent.com/670682/109979819-f98de080-7d07-11eb-8ea8-61dfaa67c6d8.png)

**Comment by erickzhao** [comment]
@dospolov Thank you for the heads-up! I've opened #593 accordingly.
