### ISSUE TITLE
Feature idea: "load" a fiddle from a gist 

### ISSUE THREAD

**Issue by ccnokes** [electron/fiddle#62]
I really enjoyed publishing a fiddle to a gist. But I'd like to make it so that anyone can easily run my gist without manually copying and pasting my code from my gist into their Electron fiddle. And maybe include a security warning when loading a gist? 

Love this project 😍

**Comment by felixrieseberg** [comment]
Oh no, I’m afraid the feature set isn’t clear 🙈 That works today! You can paste a gist idea into the address bar and it should load that Fiddle!

**Comment by ccnokes** [comment]
Oh.... yeah I didn't think to do that 😰. Adding a Load menu item near Save would have probably helped me. Thanks!

**Comment by felixrieseberg** [comment]
@ccnokes: You not finding this out on your own *is* a bug in my book. I like the “load” idea!

**Comment by ccnokes** [comment]
@felixrieseberg if you want I can work up a PR for it soon. I haven't looked at the code base at all but I imagine a menu item would be simple enough 😸
