### ISSUE TITLE
Electron 12 is broken

### ISSUE THREAD

**Issue by brandoncc** [electron/fiddle#626]
Steps to reproduce:

1. Choose Electron 12.0.2
2. Start a new fiddle
3. Save the fiddle
4. Go to the fiddle in the console
5. Run `npm i && npm run start` in the console

The version numbers should be missing in the electron browser window, and there should be errors about `process` and `require` in the dev tools console.

The fiddle runs fine in Electron Fiddle, but it must not actually be running on the chosen version.

**Comment by codebytere** [comment]
@brandoncc this is because the default of `contextIsolation` changed in Electron v12 - it's not an issue with Fiddle itself.

**Comment by brandoncc** [comment]
@codebytere I figured that out, but shouldn't fiddle create fiddles which actually work when exported? Otherwise, why even have a version dropdown? v12 needs a different setting...so it seems like Fiddle should create the correct settings based on the selected version?

**Comment by erickzhao** [comment]
Hey @brandoncc, we've amended this in #594. Fiddle will grab its content from the appropriate branches in `electron-quick-start` instead of the outdated hardcoded template.

If everything runs smoothly, the next release containing this fix should be out this morning.

**Comment by codebytere** [comment]
Closed by https://github.com/electron/fiddle/pull/594
