### ISSUE TITLE
Only four editors allowed in the UI at once

### ISSUE THREAD

**Issue by codebytere** [electron/fiddle#634]
Intuitively,  I would assume that I should be able to show all 5 available editors at once, or be given a warning if this isn't the case. However, if four are showing and one is disabled, when you click to show/enable the fifth in the command bar the eye changes but it does not show up in view unless i remove another one of the currently-shown editors. It does add itself, but I need to scroll down and as such i think users might be a little confused. Maybe we should consider resizing?

<img width="1257" alt="Screen Shot 2021-03-31 at 5 35 53 PM" src="https://user-images.githubusercontent.com/2036040/113171406-49bf6c00-91fc-11eb-858c-628787c7a4a3.png">

**Comment by thewheat** [comment]
I think this issue is a duplicate of #690 which details that the editor is pushed off the view due to the console

**Comment by codebytere** [comment]
Yep let's close this as a duplicate of #690
