### ISSUE TITLE
Have an option to keep versions of Electron in zipped rather than unzipped form

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#644]
Inspired by https://github.com/electron/fiddle/issues/638 and shares the same goal of saving disk space, but they're two different ideas that could both be implemented.

A zipped Electron release is about 40% the size of an unzipped one, and we have a _lot_ of Electron versions. It would be nice if Fiddle had an option to keep the downloads in zipped form and then unzipped only as needed, e.g. when selecting a new version in the dropdown. Unzipping is fast.

IMO this would be best as a setting that users can opt out of. I know that @codebytere and I [both use](https://xkcd.com/1172/) Fiddle as a de facto Electron version manager even when running code from the command line

**Comment by dragonDScript** [comment]
I suggest storing unzipped versions on /tmp as they would be removed on every boot.

**Comment by aryanshridhar** [comment]
Closing it! (handled in #1134)
