### ISSUE TITLE
Changing electron version reloads the default fiddle

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#665]
To repro:

1. load a fiddle
2. change the electron version with the selector in the top-left

Expected behavior:

Fiddle contents remains unchanged

Actual behavior:

Fiddle contents replaced with default fiddle

**Comment by codebytere** [comment]
@nornagon what version of Fiddle? what versions are you switching between? I can't repro this on macOS with `0.22.0` 🤔

**Comment by erickzhao** [comment]
I believe I've encountered this before, I'll try to reproduce as well.

**Comment by nornagon** [comment]
v0.22.0, and switching between any version of Electron did it. It doesn't seem to be reproducing any more though 🤔 

Pretty sure it's a real bug that's still around though, I'm not sure exactly what circumstances bring it about.

**Comment by nornagon** [comment]
I'm able to reliably reproduce this still in v0.25.1.

Steps:

1. Launch Electron Fiddle
2. Paste https://gist.github.com/dachuanhouhou/37055f48d16c97dc4e6f47b241a8898f into the "Load Fiddle" box
3. Click "Load Fiddle"
4. Change versions

the default fiddle will be re-loaded.

I think some logic here must be at fault?

https://github.com/electron/fiddle/blob/fba74a86c46c27d2c8ad1b74726c163e28af673d/src/renderer/state.ts#L489-L495

cc @ckerr who touched that code recently.

**Comment by ckerr** [comment]
I believe this is working in main and that what's happening is that 0.25.1 mistakenly didn't include the code you're linking.

**Comment by codebytere** [comment]
Fixed in https://github.com/electron/fiddle/pull/754
