### ISSUE TITLE
[Bug]: console.log output not shown

### ISSUE THREAD

**Issue by xmedeko** [electron/fiddle#668]
When I put `console.log` into:
```js
app.on('window-all-closed', function () {
  console.log('window-all-closed')
  app.quit()
})
```
Then, the log is not visible in the Fiddle's output window. The log shows after I start the app again, see (some logs removed):
```
Electron v12.0.5 started.
Electron exited with code 0.
Electron v12.0.5 started.
window-all-closed
```

**Comment by erickzhao** [comment]
I feel like I've ran into this before on Windows. Is that the OS you're using @xmedeko? Thanks for the report!

**Comment by xmedeko** [comment]
Yes, Window 10, 64 bit.

**Comment by codebytere** [comment]
I also see this fairly often - it looks like stdout is just flushing improperly?

**Comment by ckerr** [comment]
@codebytere what is this also on Windows that you see it, or  elsewhere?

[this](https://github.com/electron/fiddle/blob/master/src/renderer/state.ts#L629) looks suspicious but I don't know if that is literally this bug report or if it's just adjacent?

**Comment by codebytere** [comment]
@ckerr windows-only
