### ISSUE TITLE
Save (Ctrl+S) opens the main folder where the project resides

### ISSUE THREAD

**Issue by tosho** [electron/fiddle#69]
When I hit Ctrl+S to save Nautilius opens the parent folder of where the project is created.
Is this a bug or a feature?

running Ubuntu 18.04.1

**Comment by felixrieseberg** [comment]
Thank you for reporting! ...kind of both 😅We open the destination folder once saved, but we shouldn't do it for a quick keyboard save. I'll fix that today!
