### ISSUE TITLE
Console bumps editors off bottom of viewport

### ISSUE THREAD

**Issue by timfish** [electron/fiddle#690]
When opening the console, it bumps editors off the bottom and you can't scroll the entire viewport to get to them.

This might be intentional but I spent a while thinking I'd somehome lost an editor!

![console-bump](https://user-images.githubusercontent.com/1150298/117338278-4885fc80-ae96-11eb-99ef-0f656d3d2552.gif)

**Comment by thewheat** [comment]
I think this is now fixed

**14 editors no console**
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/892961/194760665-0ce0d979-5941-47a6-a231-bb8ad1e58331.png">

**14 editors with console**
- all still showing
<img width="1253" alt="image" src="https://user-images.githubusercontent.com/892961/194760686-6a58c435-5eba-4a29-8380-2c9d767b933a.png">

* * * 
 
There is now a separate issue with the editor listing is not scrollable and is missiing the top line when you have so many files. Will open a separate issue for thtat
<img width="670" alt="image" src="https://user-images.githubusercontent.com/892961/194760979-e47c16de-467e-4bfb-8e1f-9991d676c8e5.png">

**Comment by BlackHole1** [comment]
> I think this is now fixed
@thewheat Thanks for your feelback!
