### ISSUE TITLE
Hidden editors won't run when launching a Fiddle

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#704]
Repro steps:

* Open default Fiddle
* Hide `main.js` editor
* Launch Fiddle

The app won't launch because it can't find `main.js`

**Comment by codebytere** [comment]
@erickzhao was this not intended? i agree we might not want this behavior but i always thought it was intentionally written this way, since this same logic also applies to what files get uploaded when publishing to gist or saving to disk

**Comment by vhashimotoo** [comment]
this really looks like a regression because in version 0.22 when closing editors, fiddle is run with the content of all files, even if them is not visible

**Comment by codebytere** [comment]
@vhashimotoo ah ok yeah i see what you mean - you're right!

**Comment by codebytere** [comment]
Looks like this was introduced by https://github.com/electron/fiddle/pull/679

**Comment by codebytere** [comment]
I think this may actually have been fixed? Don't see it in latest `0.23.2` 🤔

**Comment by vhashimotoo** [comment]
looks like, maybe #683 change this behaviour again

**Comment by erickzhao** [comment]
Yup, seems like 0.23.2 reverted the behaviour to what it was before. I'll close this now!
