### ISSUE TITLE
Enhancement: better sorting logic in the version selector

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#726]
When I type "5" in the version selector box, the first suggestion is 15.0.0-nightly.\*, followed by 8.5.\*, followed by 5.*.

Ideally, the 5.* versions would come first.

**Comment by erickzhao** [comment]
I think there's support for better filtering through the `itemPredicate` prop in https://blueprintjs.com/docs/#select/select-component. Will have to do more investigating!
