### ISSUE TITLE
New logging window makes it impossible to copy/paste logs separately from timestamps

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#747]
Previously, it was possible to copy/paste just the log messages out of the log window, without the timestamps. Now, it seems the log message and the timestamp are copied together, resulting in pastes like:

```
10:50:23 AM Saving files to temp directory...
10:50:23 AM Saved files to /var/folders/_7/jm5cr84j7jd4v7btf2d3bqwm0000gn/T/tmp-41327-rDvL38ixZjEw
10:50:23 AM Electron v999.999.999 started.
10:50:23 AM [41354:0628/105023.607715:INFO:content_main_runner_impl.cc(1083)] Chrome is running in full browser mode.
10:50:24 AM [41356:0628/105024.165210:WARNING:ca_layer_tree_coordinator.mm(54)] Blank frame: No overlays or CALayers
10:50:25 AM [41354:0628/105025.306726:WARNING:discardable_shared_memory_manager.cc(432)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
10:50:25 AM [41354:0628/105025.315777:ERROR:process_posix.cc(330)] Unable to terminate process 41358: No such process (3)
10:50:25 AM 
10:50:25 AM Electron exited with code 0.
```

I'm not sure that the timestamp is all that useful to be copy/pasted? Log messages from `LOG()` already have a timestamp in them, so this is repeated information there. It might be more useful if it were 'time since app launch' and included ms? But I'd also be happy if we could just copy the raw log messages :)

This is especially relevant when a stack trace is printed out, because horizontal real estate is quite limited on github issues.

**Comment by codebytere** [comment]
Closed by https://github.com/electron/fiddle/pull/796
