### ISSUE TITLE
bug: editor context menus do not work

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#770]
Clicking on the "go to definition" or  "peek definiton"  menuitems throws an error:

```
Uncaught TypeError: Cannot read property 'id' of null
```

Tested in 0.25.2, 0.20.0, 0.16.0, 0.10.0 ... it looks like these two have never worked?

Even though these features sound cool, I'm going to go out on a limb here and say that if they've been broken for over a year and nobody's reported a bug yet, maybe these features are not something that anyone is clamoring for and not something that needs to be in the app.

**Comment by codebytere** [comment]
Closed by https://github.com/electron/fiddle/pull/808
