### ISSUE TITLE
Editors sometimes disappear when loading new Fiddle 

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#774]
Screenshot:

![image](https://user-images.githubusercontent.com/16010076/125540836-daa115f4-6d1b-4148-b76d-3c333c16551b.png)

Repro:

1. Load a Fiddle with empty files (e.g. https://gist.github.com/e27800f409182981352b68a90690c4a6)
2. Load the new default Fiddle (with <kbd>⌘</kbd> + <kbd>N</kbd>)

I bisected a bit and found out that #740 was where this bug regressed. I've also confirmed that #750 doesn't fix the issue.

**Comment by ckerr** [comment]
repro steps trigger the bug as reported. The bug is still present in today's master @ 1477bd7eff5e2cb350295d8eddc921d468fac6f5
