### ISSUE TITLE
[bug]: TypeError: Cannot read property 'version' of undefined

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#778]
Seen on Sentry.

0.25.2.

Breadcrumbs:

```
State: setVersion() got an unknown version D:Study Folder\electron\electron-v1.3.15-win32-x64
{
arguments: [
State: setVersion() got an unknown version D:\Study Folder\electron\electron-v1.3.15-win32-x64
], 
logger: console
}
exception
TypeError: Cannot read property 'version' of undefined
```

The warning and error are here at https://github.com/electron/fiddle/blob/v0.25.2/src/renderer/state.ts#L466 :+1: 

```ts
  @action public async setVersion(input: string) {
    const ver = this.getVersion(input);
    if (!ver) {
      console.warn(`State: setVersion() got an unknown version ${input}`);
      await this.setVersion(this.versionsToShow[0].version);
      return;
    }
```

So, (1), `this.versionsToShow` is an empty array. Since we (probably) always have a set of versions to use -- e.g. even if the session is offline and can't download a new list, we ship with a json file of known releases at the time that Electron Fiddle's binary was packaged -- so, just as a guess, maybe there's nothing to show because all something's in the version textentry causing everything to be filtered out?

And (2), `setVersion()` was called not with a semver version, but with an entire filepath. So at some point we're not doing input sanitization to ensure version numberts are semver. ... TBH I don't even have a guess on this one, I'm not sure where a non-semver version can be introduced into AppState.

**Comment by dsanders11** [comment]
@ckerr, I've managed to reproduce this locally on v0.27.1.

1. Under `Preferences` -> `Electron`, click "Add Local Electron Build" and add a build for a folder *not already used* in Fiddle. Give it any version you want - I used "99.0.0-alpha.4", probably best to avoid existing versions.
2. Click "Add Local Electron Build" again. Choose the same folder. There will be a message about the folder is already used, would you like to switch to that version. Click yes.
3. Observe error message pop-up, in my case: "Unknown version /Users/dsanders/Downloads/electron-v16.0.2-darwin-x64"

Will now investigate what code path leads to that stituation.
