### ISSUE TITLE
Show Me > Clipboard not working in Win10

### ISSUE THREAD

**Issue by rmda** [electron/fiddle#814]
I see this was possibly reported earlier:
https://github.com/electron/fiddle/issues/76

Neither buttons appeared to be wired up (a simple console.log in the function body is never hit when verifying using Devtools)

I see this console output in Devtools on the load of the page:

Uncaught ReferenceError: require is not defined at index.html:13 
 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
    Policy set or a policy with "unsafe-eval" enabled. This exposes users of
    this app to unnecessary security risks.
VM75 renderer_init.js:113 

For more information and help, consult
https://electronjs.org/docs/tutorial/security.
This warning will not show up
once the app is packaged.

Using Electron Fiddle 0.26.0 on Win10 20H2

**Comment by andrsdt** [comment]
Same bug here. I fixed it by modifying the `webPreferences` object in `main.js` adding the `contextIsolation: false` property, as this fiddle was written back when `contextIsolation` was `false` by default. You can check the documentation for more information about [contextIsolation](https://www.electronjs.org/docs/latest/tutorial/context-isolation/).

**Comment by thewheat** [comment]
This is a subset of https://github.com/electron/fiddle/issues/725 and good news is that there is currently a PR https://github.com/electron/fiddle/pull/888 open to address the Clipboard demo

Think this issue could be closed as a dupe for now and a should be fixed as soon as that PR is merged
