### ISSUE TITLE
Update IPC show-me to use Electron defaults

### ISSUE THREAD

**Issue by boan-anbo** [electron/fiddle#832]
https://github.com/electron/fiddle/blob/8b16dff5fd73eda95292e2c6e46ca8aa3f664f66/static/show-me/ipc/main.js#L15

needs to add `contextIsolation: false` in addition to `nodeIntegration: true` for the example to work on newer Electron versions. Otherwise `require is not defined` in browser.

**Comment by malept** [comment]
The example should be updated to use `nodeIntegration: false` and `contextIsolation: true` (which are the current defaults).
