### ISSUE TITLE
Unable to copy the entire GitHub Gist URL

### ISSUE THREAD

**Issue by bpasero** [electron/fiddle#85]
I seem to only be able to select until here:

![image](https://user-images.githubusercontent.com/900690/44456211-3be6ea80-a600-11e8-827d-ba2769ad76f3.png)

This is with macOS

**Comment by TekSiDoT** [comment]
This currently seems to work as intended.

While the element does seem to be a single input element, it actually is a span followed by an input element.

**Comment by felixrieseberg** [comment]
It does suck though, so we should probably fix that.

**Comment by BeniCheni** [comment]
Is there any hint to approach this fix?

(Can use this evening later to dig deeper on my own. But if there’s any hint, that would point my debugging to the right code area, perhaps? Still familiarizing self to the code base)

**Comment by TekSiDoT** [comment]
This would be a great place to start: [Line 112 of address-bar.tsx](https://github.com/electron/fiddle/blob/ff3fbac7ed63b76c38f039e72039379c73fbf155/src/renderer/components/address-bar.tsx#L112)

**Comment by BeniCheni** [comment]
Opened #94 to try this issue. Looking forward for your reviews. 🙏🏻
