### ISSUE TITLE
v0.26.0 not compatible with mac osx 10.10.5 

### ISSUE THREAD

**Issue by yakuv0** [electron/fiddle#883]
seems due to upgrading to electron 12.0.14 builds supports mac os 10.11+, could it be considered to make builds for 10.10.5 or any alternative ways to run on 10.10.5
regards

**Comment by erickzhao** [comment]
If you're on an unsupported OS, I would try to download an earlier binary that supports your operating system. I don't think it's tenable for us to maintain multiple builds with older, outdated Electron versions.
