### ISSUE TITLE
Can't run any fiddle as the download process does not complete

### ISSUE THREAD

**Issue by ilDon** [electron/fiddle#90]
I've just downloaded Electron Fiddle, v. `0.1.0` for Mac (`10.13.6`).

After running the intro tour, I wanted to give it a quick try, so I hit the `Run` button. Unfortunately the in-app terminal gave this message: `Could not start fiddle: Electron 2.0.7 not downloaded yet. Please wait for it to finish downloading before running the fiddle. `

As my network monitor was not showing any download activity, I've tried to switch version. 

When selecting any other version, the button `Run` switches to `Downloading`, but it looks like it is not actually downloading anything. My network monitor still says that the download speed is around 0-1 kb/s. If i press the button while is says `Downloading`, I still get the message `Could not start fiddle: Electron 2.0.7 not downloaded yet. Please wait for it to finish downloading before running the fiddle.`.

I am on a fiber connection, usually the download speed is around 2 MB/s.

Additionally, before displaying the "still downloading message", in the console I also get the following messages:

    Saving files to temp directory...
    Saved files to /var/folders/3w/0pctr_7n4xl4g49yrfn147tr0000gn/T/tmp-86349BIhXmm8JA6i1

The path changes each time I press the `Run`/`Downloading` button, but if I try to locate it (`cmg + g`), Finder tells me that the folder does not exist.

**Comment by ilDon** [comment]
Solved in v. `0.3.0`

**Comment by remixjc** [comment]
How to resolve this problem?
