### ISSUE TITLE
Allow Fiddle to pass in CLI args to Electron binary

### ISSUE THREAD

**Issue by erickzhao** [electron/fiddle#902]
Since we've added command line args to Fiddle, we lost the ability to pass in CLI flags to the Electron binary, which can be useful for certain users.

Ref https://github.com/electron/fiddle/issues/900#issuecomment-969075252

**Comment by Crilum** [comment]
Hey, any progress on this?

**Comment by erickzhao** [comment]
Hi @Crilum, we're currently taking a break for the month of December, but I'll be putting it on my task list and hopefully getting it fixed for the next release.

**Comment by Crilum** [comment]
Ok, cool. :+1:
