### ISSUE TITLE
Each CI job is being run twice

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#906]
Reported by @malept [here](https://github.com/electron/fiddle/pull/904#issuecomment-970776861). I'm creating an issue for it here so that it doesn't get forgotten :slightly_smiling_face: 

> For possibly a future PR: it looks like each CI job is running for both pushes and PRs, which means that for PRs, it gets run twice. I think it should only be run on the default branch and PRs.

**Comment by twitharshil** [comment]
@ckerr Is this a valid issue now ? I'm open to pick this up if its a valid problem

**Comment by erickzhao** [comment]
It still is. :)

**Comment by malept** [comment]
It doesn't look like this is happening anymore, not sure why.
