### ISSUE TITLE
macOs: application does not open on mac os 10.12, is it supported?

### ISSUE THREAD

**Issue by sam-smart-byte** [electron/fiddle#907]

**Comment by erickzhao** [comment]
The Electron version we use should be supported back up to El Capitan (10.11)

**Comment by sam-smart-byte** [comment]
well... I downloaded the .dmg from [here](https://www.electronjs.org/fiddle) and once double-clicked to open it just say that the app can't be opened, 
the .dmg was downloaded multiple times on two machines running the same version of macOS and nothin' same message every time: the app couldn't be open on both of them, I didn't try the utility from the command line, I'll try when I can. 
in the meanwhile have a great day/night!

**Comment by Ttamez68A** [comment]
Zzzzz
