### ISSUE TITLE
Unable to create Fiddles that use @electron/remote

### ISSUE THREAD

**Issue by Kilian** [electron/fiddle#923]
Fiddle is clever and automatically installs `require`s it finds, but the require for @electron/remote in main is `require('@electron/remote/main')`, and trying to `npm install @electron/remote/main` fails. This means you can't create fiddle that make use of @electron/remote.

**Comment by erickzhao** [comment]
@Kilian is this still a problem with v0.27.0? The automatic installation process was removed and replace with a manual package installation UI.

**Comment by Kilian** [comment]
D'oh! Yeah this was still on 0.26. All good now :)
