### ISSUE TITLE
Editor Suggestions Overlapped By Other Editors

### ISSUE THREAD

**Issue by dsanders11** [electron/fiddle#929]
Seems like a `z-index` type of issue.

![Top-Left Editor](https://user-images.githubusercontent.com/5820654/148002597-5cd35a92-fc92-437d-98d1-186399dcf24e.png)

Note however that it seems to differ by editor, the top left editor gets its suggestions overlapped by all of the other editors (see first screenshot) while the bottom left editor's suggestions are not overlapped by the top left, but are by both editors on the right.

![Bottom-Left Editor](https://user-images.githubusercontent.com/5820654/148002635-e91f7535-0cbf-4d12-9fc0-c15450205e44.png)

**Comment by erickzhao** [comment]
Looks like a regression of #289. I'll see what changed with the code such that the old fix (#294) stopped working.

**Comment by BlackHole1** [comment]
Let me see 🧐
