### ISSUE TITLE
Clicking on filenames in the sidebar should do something

### ISSUE THREAD

**Issue by nornagon** [electron/fiddle#949]
Currently, clicking anywhere here seems to have no effect:
![Screen Shot 2022-01-20 at 3 11 52 PM](https://user-images.githubusercontent.com/172800/150436862-ebf55a89-c9e7-4632-bc04-078f88f7c536.png)

**Comment by codebytere** [comment]
@nornagon instinctively, what behavior would you _want_ to see happen there? for instance, would you want it to focus the associated editor?

**Comment by nornagon** [comment]
In particular, if the editor isn't visible, it should become visible. Focus makes sense too.
