### ISSUE TITLE
Codesigning not working for windows

### ISSUE THREAD

**Issue by milenkovic** [electron/fiddle#977]
It seems that code signing is not working for windows:
- https://github.com/electron/fiddle/runs/4875090891?check_suite_focus=true#step:7:38

Also, not sure if this file `cert.p12` is generated from any place in the code.

**Comment by BlackHole1** [comment]
see: https://www.virustotal.com/gui/file/f72ce5d38be3ddc9ee0a6b36c732e683a4c2f82dda77f9f2c3df924e798df6e0/details

<img width="507" alt="image" src="https://user-images.githubusercontent.com/8198408/156796089-42c650e3-0106-4033-9360-9a5f5695375f.png">


The file has been signed and the warning here has no effect.
