### ISSUE TITLE
Sourcemap dosen't work correctly

### ISSUE THREAD

**Issue by WhisperKarl** [electron/fiddle#982]
I compiled `.js` files through `electron-forge start --`, and the `dist` directory was like:
dist
└─  src
&ensp;&ensp;&ensp;&ensp;&ensp;          └─ main
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;                   ├── main.js
&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;                   └── main.js.map

When I wanted to set an breakpoint in `.ts` file and debug it in VS Code, the console showed an error:
`Could not read source map for [file:///Users/user/Desktop/fiddle/dist/src/main/main.js](): ENOENT: no such file or directory, open '[/Users/user/Desktop/fiddle/dist/src/src/main/main.js.map]()'`

After changing the `sourceMappingURL` at the bottom of `main.js` manually, from `../src/main/main.js.map` to `main.js.map` the error log was gone. But I still can't
 debug the `.ts` files in VS Code, the breakpoints can't go into. Then I found that I have to change the source file relative path in `main.js.map`, like from 'src/main/main.ts' to `../../src/main/main.ts`.

The `tsconfig.json` is:
```
{
  "compilerOptions": {
    "esModuleInterop": true,
    "outDir": "./dist",
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "lib": [
      "es2020",
      "dom",
      "WebWorker"
    ],
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "suppressImplicitAnyIndexErrors": true,
    "strictNullChecks": true,
    "noUnusedLocals": true,
    "noImplicitThis": true,
    "noUnusedParameters": true,
    "importHelpers": true,
    "noEmitHelpers": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "pretty": true,
    "target": "es2019",
    "jsx": "react",
    "typeRoots": [
      "./node_modules/@types"
    ],
  },
  "include": [
    "src/**/*",
    "tests/**/*"
  ],
  "exclude": [
    "node_modules/**/*"
  ],
  "formatCodeOptions": {
    "indentSize": 2,
    "tabSize": 2
  }
}
```

The `launch.js` is:
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Electron: Main",
      "type": "pwa-node",               //use the node debugger that comes with VS Code
      "request": "launch",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "${workspaceFolder}/node_modules/.bin/electron",
      "runtimeArgs": [
        "--remote-debugging-port=9223",  //open debugging port for renderer process
      ],
      "args" : ["."],
      "outputCapture": "std",
      "sourceMaps": true,
      "trace": "verboser"
      // "preLaunchTask": "npm: compile"   //recompile before debugging (execute the compile script defined in package.json)
    },
    {
      "name": "Electron: Renderer",
      "type": "pwa-chrome",             //use the Chrome debugger that comes with VS Code
      "request": "attach",
      "port": 9223,                     //use debug port opened in Electron: Main configuration
      "webRoot": "${workspaceFolder}",
      "timeout": 30000
    }
  ],
  "compounds": [                        //launch multiple configurations concurrently
    {
      "name": "Electron: All",
      "configurations": [
        "Electron: Main",
        "Electron: Renderer"
      ]
    }
  ]
}
```

How can i make the `sourceMap` work correctly?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
