### ISSUE TITLE
toolbar looks strange on Linux

### ISSUE THREAD

**Issue by ckerr** [electron/fiddle#985]
Introduced by #961. 

Before this PR, the look on Linux was:

![old-look](https://user-images.githubusercontent.com/70381/156268983-8c58c01e-868d-4b2e-a9b3-9cc13655c7a7.png)

After the PR, the look is:

![new-look](https://user-images.githubusercontent.com/70381/156269006-70c6156e-dcfa-482a-b5e6-dfefe052d3e2.png)

**Comment by dsanders11** [comment]
Looks the same on Windows, FYI.
